#include "Localization.h"
#include "ship/utils/StringHelper.h"
#include "soh/cvar_prefixes.h"
#include <libultraship/libultraship.h>
#include <unordered_map>
#include <string>
#include <set>
#include <vector>
#include <filesystem>
#include <imgui.h>

namespace SohGui {

// Simplified-Chinese translation table.
// Key = the original English UI string as it appears in the code.
// Value = Simplified Chinese. Any string not present here is left untouched.
// Entries are seeded from extracted_strings.txt (UI text passed through StringHelper::Translate).
static const std::unordered_map<std::string, std::string> gChineseTable = {
    // ---- batch 1 (extracted strings 1-200, alphabetical A-B) ----
    { "(Select \"Off\" to disable.)", "（选择“关闭”以禁用。）" },
    { "-5 will be half as much time, +5 will be 6x as much time. Affects timed switches, torches, GTG statue ", "-5 表示时间减半，+5 表示时间增至 6 倍。影响定时开关、火把、GTG 雕像" },
    { "0.25 Hearts", "0.25 颗心" },
    { "0.5 Hearts", "0.5 颗心" },
    { "1 Heart", "1 颗心" },
    { "16:10 (8:5)", "16:10 (8:5)" },
    { "2 Hearts", "2 颗心" },
    { "4 Hearts", "4 颗心" },
    { "8 Hearts", "8 颗心" },
    { "A Wallmaster follows Link everywhere, don't get caught!", "Wallmaster 会跟随林克到处走，别被抓到！" },
    { "A Wind Waker-style twinkling starfield over the night sky: a fixed bright constellation plus ", "夜空中风之杖风格的闪烁星空：固定亮星座加上" },
    { "About", "关于" },
    { "About Crowd Control", "关于人群控制" },
    { "Accessibility", "辅助功能" },
    { "Activates MSAA (multi-sample anti-aliasing) from 2x up to 8x, to smooth the edges of ", "启用 MSAA（多重采样抗锯齿），从 2x 到 8x，以平滑边缘" },
    { "Actor Shadows", "角色阴影" },
    { "Add a button to the combination", "向组合中添加一个按钮" },
    { "Additional Settings", "附加设置" },
    { "Additional Traps", "附加陷阱" },
    { "Adds 5 higher pitches for the Silver Rupee Jingle for the rooms with more than 5 Silver Rupees. ", "为含超过 5 枚银卢比的房间，银卢比铃声增加 5 个更高音。" },
    { "Adds a prompt to equip newly-obtained Swords, Shields, and Tunics.", "添加提示以装备新获得的剑、盾和衣服。" },
    { "Adds back in a delay after unpausing before the game resumes playing again, ", "恢复在取消暂停后、游戏继续前的延迟，" },
    { "Adjust the number of notes the Skull Kids play to start the first round.", "调整骷髅小子演奏以开始第一轮的音符数。" },
    { "Adjust the number of notes you need to play to end the first round.", "调整结束第一轮所需演奏的音符数。" },
    { "Adjust the number of notes you need to play to end the second round.", "调整结束第二轮所需演奏的音符数。" },
    { "Adjust the number of notes you need to play to end the third round.", "调整结束第三轮所需演奏的音符数。" },
    { "Adjust the speed that the Skull Kids play the notes.", "调整骷髅小子演奏音符的速度。" },
    { "Adjusts rate Dampe drops flames during race.", "调整达姆佩赛跑中丢火把的速率。" },
    { "Adjusts the Horizontal Culling Plane to account for Widescreen Resolutions.", "调整水平剔除平面以适应宽屏分辨率。" },
    { "Adjusts the time allowed for playback before failing.", "调整演奏失败前的允许时间。" },
    { "Adult Minimum Weight: %d lbs.", "成人最小负重：%d 磅。" },
    { "Adult Starting Ammunition: %d arrows", "成人初始弹药：%d 支箭" },
    { "Advance (Hold)", "前进（按住）" },
    { "Advance 1", "前进 1" },
    { "Advance 1 frame.", "前进 1 帧。" },
    { "Advance frames while the button is held.", "按住按钮时逐帧前进。" },
    { "Advanced Graphics Options", "高级图形选项" },
    { "After completing the mask trading sub-quest, press A and any direction on the mask ", "完成面具交易支线任务后，按 A 和面具上的任意方向" },
    { "Aim Boomerang in First-Person Mode", "在第一人称模式下瞄准回旋镖" },
    { "Aiming Reticle for Boomerang", "回旋镖的瞄准准星" },
    { "Aiming Reticle for the Bow/Slingshot", "弓/弹弓的瞄准准星" },
    { "Aiming with a Bow or Slingshot will display a reticle as with the Hookshot ", "用弓或弹弓瞄准时将显示准星，如同钩爪" },
    { "Aiming with the Boomerang will display a reticle as with the Hookshot.", "用回旋镖瞄准时将显示准星，如同钩爪。" },
    { "All", "全部" },
    { "All Dogs are Richard", "所有狗都是理查德" },
    { "All Fish are Hyrule Loaches", "所有鱼都是海拉尔泥鳅" },
    { "All Items", "所有物品" },
    { "All Major Bosses move and act twice as fast.", "所有主要 Boss 移动和攻击速度加倍。" },
    { "All Regular Enemies and Mini-Bosses move and act twice as fast.", "所有普通敌人和迷你 Boss 移动和攻击速度加倍。" },
    { "All dogs can be traded in and will count as Richard.", "所有狗都可以交易，并算作理查德。" },
    { "All fish will be caught instantly.", "所有鱼将被立即钓到。" },
    { "All##Skips", "全部##Skips" },
    { "Allow Link to enter Jabu-Jabu without feeding him a fish.", "允许林克不喂鱼进入贾布贾布。" },
    { "Allow Link to put items away without having to wait around.", "允许林克无需等待即可收起物品。" },
    { "Allow Strength Equipment to be Toggled", "允许切换力量装备" },
    { "Allow background inputs", "允许后台输入" },
    { "Allow multi-windows", "允许多窗口" },
    { "Allow the Bow and Magic Arrows to be equipped at the same time on different slots. ", "允许弓和魔法箭在不同槽位同时装备。" },
    { "Allow the Cursor to be on Any Slot", "允许光标位于任意槽位" },
    { "Allow unequipping Items", "允许卸下物品" },
    { "Allows Bombchus to explode out of bounds. Similar to GameCube and Wii VC.", "允许炸弹鼠越界爆炸。类似 GameCube 和 Wii VC。" },
    { "Allows Child Link to use a Bow with Arrows.\n", "允许儿童林克使用弓和箭。\n" },
    { "Allows Ice Arrows to melt Red Ice. May require a room reload if toggled during gameplay.", "允许冰箭融化红冰。游戏中进行切换时可能需要重新加载房间。" },
    { "Allows Light Arrows to activate Sun Switches. May require a room reload if toggled during gameplay.", "允许光箭激活太阳开关。游戏中进行切换时可能需要重新加载房间。" },
    { "Allows Link to bounce off walls when linear velocity is high enough, this is ", "当线速度足够高时，允许林克从墙壁弹开，这是" },
    { "Allows Link to freely change age by playing the Song of Time.\n", "允许林克通过演奏时之曲自由改变年龄。\n" },
    { "Allows Link to unsheathe sword without slashing automatically.", "允许林克拔剑而不自动挥砍。" },
    { "Allows Strength to be toggled on and off by pressing A on the Strength Upgrade ", "允许在力量升级上按 A 开关力量" },
    { "Allows Z-Targeting Gold Skulltulas.", "允许 Z 瞄准黄金骷髅蜘蛛。" },
    { "Allows any item to be equipped, regardless of age.\n", "允许装备任意物品，不受年龄限制。\n" },
    { "Allows controller inputs to be picked up by the game even when the game window isn't ", "允许游戏即使窗口未" },
    { "Allows controller navigation of the port menu (Settings, Enhancements,...)\nCAUTION: ", "允许用控制器导航端口菜单（设置、增强功能等）\n注意：" },
    { "Allows cycling between different arrow types (Normal, Fire, Ice, Light) while aiming the bow. ", "允许在瞄准弓时在不同箭头类型（普通、火、冰、光）间循环。" },
    { "Allows dogs to follow you anywhere you go, even if you leave the Market.", "允许狗跟随你到任何地方，即使离开市场。" },
    { "Allows equipment to be removed by toggling it on/off\n the equipment subscreen.", "允许通过开关在装备子界面移除装备\n。" },
    { "Allows equipping Shields, Tunics and Boots to C-Buttons/D-pad.", "允许将盾、外衣和靴装备到 C 按钮/方向键。" },
    { "Allows exiting Hyrule Castle Market Town to Hyrule Field at night by speaking to the guard ", "允许夜间通过与守卫对话从海拉尔城市场镇退出到海拉尔平原" },
    { "Allows graves to be pulled when child during the day.", "允许儿童在白天拉坟墓。" },
    { "Allows masks to be equipped normally from the pause menu as adult.", "允许成人从暂停菜单正常装备面具。" },
    { "Allows multiple windows to be opened at once. Requires a reload to take effect.", "允许同时打开多个窗口。需要重新加载生效。" },
    { "Allows the Lon Lon Ranch Obstacle Course reward to be shared across time periods.", "允许隆隆牧场障碍赛奖励跨时间段共享。" },
    { "Allows the cursor on the pause menu to be over any slot. Sometimes required in Randomizer ", "允许暂停菜单上的光标位于任意槽位。随机化中有时需要" },
    { "Allows unequipping items from C-Buttons/D-pad by hovering over an equipped ", "允许通过将光标悬停在已装备的物品上，从 C 按钮/方向键卸下" },
    { "Allows you to change the number of days it takes for ", "允许你改变所需的天数" },
    { "Allows you to control a Bombchu after dropping it.\n", "允许你在丢下炸弹鼠后控制它。\n" },
    { "Allows you to have \"Link\" as a premade file name.", "允许你使用“Link”作为预设文件名。" },
    { "Allows you to use any item at any location", "允许你在任何地点使用任意物品" },
    { "Allows you to walk through walls.", "允许你穿墙。" },
    { "Also cast a pool from Link's fairy (Navi). Navi darts around quickly, so her pool moves a lot.", "同时从林克的精灵（娜薇）处投射光池。娜薇快速飞舞，所以她的光池移动很多。" },
    { "Always", "总是" },
    { "Always Show Dungeon Entrances", "总是显示地牢入口" },
    { "Always Win Dampe Digging Game", "总是赢达姆佩挖掘游戏" },
    { "Always Win Goron Pot", "总是赢哥隆壶" },
    { "Always get the Heart Piece/Purple Rupee from the Spinning Goron Pot.", "总是从旋转哥隆壶获得心之碎片/紫色卢比。" },
    { "Always shows dungeon entrance icons on the Minimap.", "总是在小地图上显示地牢入口图标。" },
    { "Always win the Heart Piece/Purple Rupee on the first dig in Dampe's Grave Digging game. ", "在达姆佩坟墓挖掘游戏第一次挖掘时总是赢得心之碎片/紫色卢比。" },
    { "Always: Link must always play Zelda's Lullaby to open the waterfall entrance to Zora's Domain.\n", "总是：林克必须总是演奏塞尔达的摇篮曲以打开佐拉领地的瀑布入口。\n" },
    { "Ammo", "弹药" },
    { "Ammo Traps", "弹药陷阱" },
    { "Ammo counts in the pause menu will work correctly regardless of the position of items in the Inventory.", "暂停菜单中的弹药计数将正确工作，不受物品在背包中位置影响。" },
    { "Amy's block pushing puzzle instantly solved.", "艾米的推块谜题立即解决。" },
    { "Animated Link in Pause Menu", "暂停菜单中的动画林克" },
    { "Animations", "动画" },
    { "Answer Navi Prompt with L Button", "用 L 按钮回应娜薇提示" },
    { "Anti-aliasing (MSAA)", "抗锯齿（MSAA）" },
    { "Any Ocarina", "任意陶笛" },
    { "Any Ocarina + Master Sword", "任意陶笛 + 大师之剑" },
    { "Are you sure you want to quit SoH?", "你确定要退出 SoH 吗？" },
    { "Arrow Cycle", "箭循环" },
    { "Ask to Equip New Items", "询问是否装备新物品" },
    { "Aspect Ratio", "宽高比" },
    { "AspectRatioCustom", "自定义宽高比" },
    { "AspectSep", "宽高比分隔" },
    { "Assignable Shields, Tunics and Boots", "可分配的盾、外衣和靴" },
    { "Audio", "音频" },
    { "Audio API", "音频 API" },
    { "Audio API (Needs reload)", "音频 API（需重新加载）" },
    { "Audio Fixes", "音频修复" },
    { "Authentic", "原版" },
    { "Automatically sets scale factor to fit window. Only available in Pixel Perfect Mode.", "自动设置缩放比例以适配窗口。仅在像素完美模式下可用。" },
    { "Autosave", "自动保存" },
    { "Background Opacity", "背景不透明度" },
    { "Be sure to explore the Presets and Enhancements Menus for various Speedups and Quality of life changes!", "请务必探索预设和增强功能菜单，获取各种加速和生活质量改动！" },
    { "Beta Quest", "测试任务" },
    { "Beta Quest World: %d", "测试任务世界：%d" },
    { "Better Ammo Rendering in Pause Menu", "暂停菜单中更好的弹药渲染" },
    { "Better Bombchu Shopping", "更好的炸弹鼠购物" },
    { "Better Debug Warp Screen", "更好的调试传送屏幕" },
    { "Better Farore's Wind", "更好的法拉薇之风" },
    { "Better Owl", "更好的猫头鹰" },
    { "Biggoron Forge Time: %d days", "比贡锻造时间：%d 天" },
    { "Block Pushing Speed +%d", "推块速度 +%d" },
    { "Blue", "蓝色" },
    { "Blue Fire Arrows", "蓝火箭" },
    { "Blue Fire dropped from bottle can be bottled.", "瓶子中掉落的蓝火可以被装入瓶。" },
    { "Bomb Timer Multiplier: %.2fx", "炸弹计时器倍数：%.2f 倍" },
    { "Bomb Traps", "炸弹陷阱" },
    { "Bombchu Bowling", "炸弹鼠保龄球" },
    { "Bombchu Count: %d bombchus", "炸弹鼠数量：%d" },
    { "Bombchus Out of Bounds", "炸弹鼠越界" },
    { "Bombchus do not sell out when bought, and a 10 pack of Bombchus costs 99 rupees ", "炸弹鼠购买后不会售罄，10 个炸弹鼠售价 99 卢比" },
    { "Bombchus will sometimes drop in place of Bombs.", "炸弹鼠有时会替代炸弹掉落。" },
    { "Bonk Damage Multiplier", "撞击伤害倍数" },
    { "Bonking into Trees will have a chance to drop up to 3 Sticks. Must have obtained sticks previously.", "撞树有机会掉落最多 3 根木棒。必须先获得过木棒。" },
    { "Boomerang", "回旋镖" },
    { "Boot", "启动" },
    { "Boot Sequence", "启动序列" },
    { "Both Ages", "两个年龄" },
    { "Bottles", "瓶子" },
    { "Bottom Left", "左下" },
    { "Bottom Right", "右下" },
    { "Bounce off Walls", "从墙壁弹开" },
    { "Bow / Slingshot", "弓 / 弹弓" },
    { "Bow as Child/Slingshot as Adult", "儿童用弓/成人用弹弓" },
    { "Brightness of the lit side. Higher = brighter highlights.", "受光面的亮度。越高 = 高光越亮。" },
    { "Brown", "棕色" },
    { "Buffers your inputs to be executed a specified amount of frames later.", "缓冲你的输入，使其在指定帧数后执行。" },
    { "Bugs don't Despawn", "虫子不消失" },
    { "Bunny Hood Effect", "兔帽效果" },
    { "Burn Traps", "燃烧陷阱" },
    { "Button Combination:", "按钮组合：" },
    { "Buttons that activate Speed Modifier 1.\n\n", "激活速度修改器 1 的按钮。\n\n" },
    { "Buttons to activate target switching.", "激活目标切换的按钮。" },
    { "Camera Fixes", "相机修复" },
    { "Cancel", "取消" },
    { "Casts a pool of light from each point light (torch, fairy, ...) onto the surrounding world ", "从每个点光源（火把、精灵等）向周围世界投射光池" },
    { "Causes respawning enemies, like Stalchildren, to appear on land near bodies of water. ", "导致重生敌人（如斯塔尔德伦）出现在水体附近的陆地。" },
    { "Causes your Wallet to fill and empty faster when you gain or lose money.", "当你获得或失去金钱时，使钱包充值和清空更快。" },
    { "Cel Shading", "卡通渲染" },
    { "Change Age", "改变年龄" },
    { "Change aiming for the Boomerang from Third-Person to First-Person to see past Link's head.", "将回旋镖的瞄准从第三人称改为第一人称，以看清林克头部前方。" },
    { "Changes Heart Piece and Heart Container functionality.\n\n", "改变心之碎片和心之容器的功能。\n\n" },
    { "Changes the Rupee in the Wallet icon to match the wallet size you currently have.", "改变钱包图标中的卢比以匹配当前钱包大小。" },
    { "Changes the Theme of the Menu Widgets.", "更改菜单控件的主题。" },
    { "Changes the behavior of debug file select creation (creating a save file on slot 1 ", "改变调试文件选择创建的行为（在槽位 1 创建存档" },
    { "Changes the menu display from overlay to windowed.", "将菜单显示从叠加改为窗口化。" },
    { "Changes the scaling of the ImGui menu elements.", "更改 ImGui 菜单元素的缩放。" },
    { "Changes the speed of sections of text that normally are paced slower than the text surrounding it.", "改变通常比周围文本节奏慢的文本段落的速度。" },
    { "Check Tracker", "检查追踪器" },
    { "Check Tracker Settings", "检查追踪器设置" },
    { "Child Minimum Weight: %d lbs.", "儿童最小负重：%d 磅。" },
    { "Child Starting Ammunition: %d seeds", "儿童初始弹药：%d 种子" },
    { "Child Toggle", "儿童切换" },
    { "Chinese", "中文" },
    { "Clear", "清除" },
    { "Clear Config", "清除配置" },
    { "Clear Cutscene Pointer", "清除过场指针" },
    { "Clear Devices", "清除设备" },
    { "Clears the cutscene pointer to a value safe for wrong warps.", "将过场指针清除为对错误传送安全的值。" },
    { "Click to disable N64 mode", "点击禁用 N64 模式" },
    { "Climb Everything", "攀爬一切" },
    { "Close Menu (Esc)", "关闭菜单（Esc）" },
    { "Clouds", "云" },
    { "Color Temple of Time's Medallions", "为时之庙的勋章上色" },
    { "Configure what happens when starting or resetting the game.\n\n", "配置开始或重置游戏时发生的情况。\n\n" },
    { "Connect to Crowd Control", "连接到人群控制" },
    { "Connecting...", "连接中……" },
    { "Connecting...##Sail", "连接中……##Sail" },
    { "Consistent Vanish", "一致的消失" },
    { "Containers Match Contents", "容器匹配内容" },
    { "Containers of Agony", "痛苦容器" },
    { "Continue holding START button when unpausing to only advance a single frame and then re-pause.", "在取消暂停时继续按住 START 按钮，仅前进一帧然后重新暂停。" },
    { "Controller Bindings", "控制器绑定" },
    { "Controls", "控制" },
    { "Convenience", "便捷功能" },
    { "Core Audio", "核心音频" },
    { "Correctly centers the Navi text prompt on the HUD's C-Up button.", "将娜薇的提示文本正确居中到 HUD 的 C 上按钮。" },
    { "Coverage", "覆盖范围" },
    { "Crawl Speed %dx", "爬行速度 %d 倍" },
    { "Creates a new random seed value to be used when generating a randomizer", "创建用于生成随机化器的新的随机种子值" },
    { "Critical", "严重" },
    { "Crowd Control is a platform that allows viewers to interact ", "人群控制是一个允许观众互动的平台" },
    { "Cuccos Needed By Anju: %d", "安茹所需公鸡数：%d" },
    { "Cuccos Stay Put Multiplier: %dx", "公鸡停留倍数：%d 倍" },
    { "Cuccos will stay in place longer after putting them down, by a multiple of the value of the slider.", "放下公鸡后，它们会按滑块值的倍数停留更久。" },
    { "Cull Glitch Useful Actors", "剔除对故障有用的角色" },
    { "Current FPS", "当前 FPS" },
    { "Cursor Always Visible", "光标始终可见" },
    { "Custom", "自定义" },
    { "Customize Behavior##Bowling", "自定义行为##Bowling" },
    { "Customize Behavior##Fishing", "自定义行为##Fishing" },
    { "Customize Behavior##Frogs", "自定义行为##Frogs" },
    { "Customize Behavior##LostWoods", "自定义行为##LostWoods" },
    { "Customize Behavior##Shooting", "自定义行为##Shooting" },
    { "Cutscenes", "过场动画" },
    { "Cycles through colors on a timer\nOverwrites previously chosen color", "按计时器循环切换颜色\n覆盖之前选择的颜色" },
    { "Damage Multiplier", "伤害倍数" },
    { "Dampe Appears All Night", "达姆佩整夜出现" },
    { "Dampe Drop Rate", "达姆佩掉落率" },
    { "Dampe's Inferno", "达姆佩的地狱" },
    { "Dark Blue", "深蓝" },
    { "Dark Gray", "深灰" },
    { "Dark Green", "深绿" },
    { "Dark Red", "深红" },
    { "Death Traps", "死亡陷阱" },
    { "Debug", "调试" },
    { "Debug Mode", "调试模式" },
    { "Debug Save File Mode", "调试存档文件模式" },
    { "Debug Warp Screen", "调试传送屏幕" },
    { "Debug Warp Screen Translation", "调试传送屏幕翻译" },
    { "Default", "默认" },
    { "Deku Nuts Explode Bombs", "代库坚果引爆炸弹" },
    { "Deku Stick", "代库木棒" },
    { "Deku Sticks:", "代库木棒：" },
    { "Delete File on Death", "死亡时删除文件" },
    { "Depth of the Wind Waker size pulse — the pool's dominant flicker. The orb ", "风之杖尺寸脉动深度——光池的主要闪烁。光球" },
    { "Despawn Timers", "消失计时器" },
    { "Desync Fixes", "不同步修复" },
    { "Dev Tools", "开发工具" },
    { "DirectX", "DirectX" },
    { "Disable 2D Pre-Rendered Scenes", "禁用 2D 预渲染场景" },
    { "Disable Black Bar Letterboxes", "禁用黑边信箱" },
    { "Disable Bomb Billboarding", "禁用炸弹广告牌" },
    { "Disable Crit Wiggle", "禁用暴击摆动" },
    { "Disable Fixed Camera", "禁用固定相机" },
    { "Disable Grotto Fixed Rotation", "禁用洞窟固定旋转" },
    { "Disable HUD Heart Animations", "禁用 HUD 心形动画" },
    { "Disable Haunted Wasteland Sandstorm", "禁用鬼魅荒野沙暴" },
    { "Disable Hot/Underwater Warning Text", "禁用高温/水下警告文本" },
    { "Disable Idle Camera Re-Centering", "禁用空闲相机重新居中" },
    { "Disable Jabu Wobble", "禁用贾布晃动" },
    { "Disable Kokiri Fade", "禁用科克里淡入" },
    { "Disable LOD", "禁用细节层次" },
    { "Disable Link Spinning With Goron Pot", "禁用林克随哥隆壶旋转" },
    { "Disable Link's Sword Trail", "禁用林克剑光轨迹" },
    { "Disable Random Camera Wiggle at Low Health.", "禁用低血量时随机相机摆动。" },
    { "Disable Screen Flash for Finishing Blow", "禁用终结一击的屏幕闪光" },
    { "Disable Title Card", "禁用标题卡" },
    { "Disable the geometry wobble and camera distortion inside Jabu.", "禁用贾布内部的几何晃动和相机扭曲。" },
    { "Disabled", "已禁用" },
    { "Disabled: Paths vanish more the higher the resolution (Z-Fighting is based on resolution).\n", "已禁用：分辨率越高，路径消失越多（Z 冲突基于分辨率）。\n" },
    { "Disables 2D pre-rendered backgrounds. Enable this when using a mod that ", "禁用 2D 预渲染背景。使用修改此类背景的模组时启用" },
    { "Disables Black Bar Letterboxes during cutscenes and Z-Targeting. NOTE: There may be minor visual ", "禁用过场动画和 Z 瞄准时的黑边信箱。注意：可能会有轻微的视觉" },
    { "Disables Grottos rotating with the Camera. To be used in conjuction with mods that want to ", "禁用洞窟随相机旋转。与需要此功能的模组配合使用" },
    { "Disables Heart Drops, but not Heart Placements, like from a Deku Scrub running off.\n", "禁用心形掉落，但不禁用心形放置，例如德库树精逃跑时。\n" },
    { "Disables Random Drops, except from the Goron Pot, Dampe, and Bosses.", "禁用随机掉落，哥隆壶、达姆佩和 Boss 除外。" },
    { "Disables bombs always rotating to face the camera. To be used in conjunction with mods that want to ", "禁用炸弹始终旋转面向相机。与需要此功能的模组配合使用" },
    { "Disables sandstorm effect in Haunted Wasteland.", "禁用鬼魅荒野的沙暴效果。" },
    { "Disables the Beating Animation of the Hearts on the HUD.", "禁用心形 HUD 的跳动动画。" },
    { "Disables the automatic re-centering of the camera when idle.", "禁用空闲时相机的自动重新居中。" },
    { "Disables the fixed camera in maps that use 2D pre-rendered backgrounds. Enable this when using a mod ", "在使用 2D 预渲染背景的地图中禁用固定相机。使用此类模组时启用" },
    { "Disables the sword trail effect when swinging Link's sword. Useful when ", "禁用挥动林克之剑时的剑光轨迹效果。适用于" },
    { "Disables the white screen flash on enemy kill.", "禁用击杀敌人时的白屏闪光。" },
    { "Disables warning text when you don't have on the Goron/Zora Tunic ", "当未穿着哥隆/佐拉外衣时禁用警告文本" },
    { "Displays a \"Mystery Item\" model in place of any freestanding/GS/shop items that were shuffled, ", "为任何被洗牌的静止/黄金骷髅/商店物品显示“神秘物品”模型，" },
    { "Displays a test notification.", "显示一个测试通知。" },
    { "Displays a tick in the top center of the screen to help with glitch line-ups in SoH, since traditional ", "在屏幕顶部中央显示一个刻度，以帮助在 SoH 中对齐故障，因为传统的" },
    { "Displays an icon and plays a sound when Stone of Agony should be activated, for those without rumble.", "当痛苦之石应被激活时显示图标并播放声音，供没有震动的玩家使用。" },
    { "Displays the Search menu as a sidebar entry in Settings instead of in the header.", "将搜索菜单显示为设置中的侧边栏条目，而非标题栏。" },
    { "Dogs Follow You Everywhere", "狗跟随你到各处" },
    { "Don't Require Input for Credits Sequence", "过场字幕序列不需要输入" },
    { "Don't affect jump distance/velocity", "不影响跳跃距离/速度" },
    { "Don't increase crawl speed when exiting glitch-useful crawlspaces.", "从对故障有用的爬行空间退出时不增加爬行速度。" },
    { "Don't scale image to fill window.", "不缩放图像以填满窗口。" },
    { "Don't skip cutscenes that are associated with useful glitches. Currently, it is ", "不跳过与有用故障相关的过场动画。目前，它" },
    { "Double (2x)", "两倍（2x）" },
    { "Draw Distance", "绘制距离" },
    { "Draws a debug ray from each actor for every candidate light (coloured by the light, longer ", "从每个角色向每个候选光源绘制调试射线（按光源着色，越长" },
    { "Draws the Wind Waker sky only on the left half of the screen, leaving the original sky ", "仅将风之杖天空绘制在屏幕左半部分，保留原始天空" },
    { "Draws the actual 3D shadow volume translucently so you can see its shape: black top/bottom caps, ", "半透明地绘制实际的 3D 阴影体积，以便查看其形状：黑色顶/底盖，" },
    { "Drift Speed", "漂移速度" },
    { "Drifting Wind Waker-style puffy clouds across the sky, plus the wispy cloud band around the ", "风之杖风格蓬松云朵在天空漂移，加上环绕的稀薄云带" },
    { "Drops", "掉落物" },
    { "Drops Don't Despawn", "掉落物不消失" },
    { "Drops from enemies, grass, etc. don't disappear after a set amount of time.", "敌人、草等掉落的物品在一段时间后不会消失。" },
    { "Dungeons", "地牢" },
    { "Dungeons (MQ)", "地牢（MQ）" },
    { "Dungeons (Vanilla)", "地牢（原版）" },
    { "Dungeons Random", "地牢随机" },
    { "Dungeons Random (Seeded)", "地牢随机（种子）" },
    { "Duration (seconds):", "持续时间（秒）：" },
    { "Dying will delete your file.\n\n", "死亡将删除你的文件。\n\n" },
    { "Dynamic Wallet Icon", "动态钱包图标" },
    { "EXPERIMENTAL", "实验性" },
    { "Early Eyeball Frog", "提前的眼球蛙" },
    { "Easy Frame Advancing with Pause", "暂停时轻松逐帧前进" },
    { "Easy ISG", "轻松无限剑术故障" },
    { "Easy QPA", "轻松 QPA" },
    { "Empty Bottles Faster", "更快清空瓶子" },
    { "Enable 3D Dropped Items/Projectiles", "启用 3D 掉落物品/抛射物" },
    { "Enable Actor Shadows", "启用角色阴影" },
    { "Enable Beta Quest", "启用测试任务" },
    { "Enable Bombchu Drops", "启用炸弹鼠掉落" },
    { "Enable Cel Shading", "启用卡通渲染" },
    { "Enable Clouds", "启用云" },
    { "Enable Deku Stick Light Casting", "启用代库木棒光投射" },
    { "Enable Light Casting", "启用光投射" },
    { "Enable Navi Light Casting", "启用娜薇光投射" },
    { "Enable Other Fairy Light Casting", "启用其他精灵光投射" },
    { "Enable Passage of Time on File Select", "在文件选择界面启用时间流逝" },
    { "Enable Stars", "启用星空" },
    { "Enable Visual Guard Vision", "启用可视守卫视野" },
    { "Enable Vsync", "启用垂直同步" },
    { "Enable Wind Wisps", "启用风之精" },
    { "Enable advanced settings.", "启用高级设置。" },
    { "Enable##CrowdControl", "启用##CrowdControl" },
    { "Enable##Sail", "启用##Sail" },
    { "Enables Debug Mode, allowing you to select maps with L + R + Z, noclip ", "启用调试模式，允许你用 L + R + Z 选择地图、穿墙" },
    { "Enables Ivan the Fairy upon the next map change. Player 2 can control Ivan and press the C-Buttons to ", "在下次地图切换时启用精灵伊万。玩家 2 可控制伊万并按 C 按钮" },
    { "Enables Skulltula Debug, when moving the cursor in the menu above various ", "启用黄金骷髅调试，在菜单中将光标移到各种" },
    { "Enables Windowed Fullscreen Mode.", "启用窗口化全屏模式。" },
    { "Enables additional Trap variants.", "启用额外的陷阱变体。" },
    { "Enables text to speech for in game dialog", "为游戏内对话启用文字转语音" },
    { "Enables the registry editor.", "启用注册表编辑器。" },
    { "Enables the separate Actor Viewer Window.", "启用独立的角色查看器窗口。" },
    { "Enables the separate Additional Timers Window.", "启用独立的附加计时器窗口。" },
    { "Enables the separate Audio Editor Window.", "启用独立的音频编辑器窗口。" },
    { "Enables the separate Bindings Window.", "启用独立的按键绑定窗口。" },
    { "Enables the separate Check Tracker Settings Window.", "启用独立的检查追踪器设置窗口。" },
    { "Enables the separate Collision Viewer Window.", "启用独立的碰撞查看器窗口。" },
    { "Enables the separate Console Window.", "启用独立的控制台窗口。" },
    { "Enables the separate Cosmetics Editor Window.", "启用独立的化妆编辑器窗口。" },
    { "Enables the separate Display List Viewer Window.", "启用独立的显示列表查看器窗口。" },
    { "Enables the separate Entrance Tracker Settings Window.", "启用独立的入口追踪器设置窗口。" },
    { "Enables the separate Gameplay Stats Window.", "启用独立的游戏统计窗口。" },
    { "Enables the separate Gfx Debugger Window.", "启用独立的图形调试器窗口。" },
    { "Enables the separate Hook Debugger Window.", "启用独立的钩子调试器窗口。" },
    { "Enables the separate Input Viewer Settings Window.", "启用独立的输入查看器设置窗口。" },
    { "Enables the separate Item Tracker Settings Window.", "启用独立的物品追踪器设置窗口。" },
    { "Enables the separate Message Viewer Window.", "启用独立的消息查看器窗口。" },
    { "Enables the separate Mod Menu Window.", "启用独立的模组菜单窗口。" },
    { "Enables the separate Randomizer Settings Window.", "启用独立的随机化器设置窗口。" },
    { "Enables the separate Save Editor Window.", "启用独立的存档编辑器窗口。" },
    { "Enables the separate Stats Window.", "启用独立的统计窗口。" },
    { "Enables the separate Time Splits Window.", "启用独立的时间分段窗口。" },
    { "Enables the separate Value Viewer Window.", "启用独立的数值查看器窗口。" },
    { "Enemies", "敌人" },
    { "Enemies spawned by CrowdControl won't be considered for \"clear enemy ", "人群控制生成的敌人不计入“清除敌人”" },
    { "Enemy Health Bars", "敌人生命条" },
    { "Enemy Name Tags", "敌人名称标签" },
    { "English", "英语" },
    { "Enhancements", "增强功能" },
    { "Entrance Tracker", "入口追踪器" },
    { "Entrance Tracker Settings", "入口追踪器设置" },
    { "Epona Boost", "伊波娜加速" },
    { "Equip Items on Dpad", "在方向键上装备物品" },
    { "Equip Multiple Arrows at Once", "一次装备多支箭" },
    { "Equip items and equipment on the D-pad. If used with \"D-pad on Pause Screen\", you must ", "在方向键上装备物品和装备。若与“暂停界面方向键”一起使用，你须" },
    { "Equipment", "装备" },
    { "Equipment Toggle", "装备切换" },
    { "Error", "错误" },
    { "Every fish in the Fishing Pond will always be a Hyrule Loach.\n\n", "钓鱼池中的每条鱼都始终是海拉尔泥鳅。\n\n" },
    { "Exclude Actors that are useful for Glitches from the extended culling ranges. Some actors may still draw ", "将有用故障的角色排除在扩展剔除范围之外。某些角色可能仍会绘制" },
    { "Exclude Glitch-Aiding Crawlspaces", "排除辅助故障的爬行空间" },
    { "Exclude Glitch-Aiding Cutscenes", "排除辅助故障的过场动画" },
    { "Excluded Locations", "排除的地点" },
    { "Exit Market at Night", "夜间离开市场" },
    { "Explosions are now a static size, like in Majora's Mask and OoT3D. Makes Bombchu ", "爆炸现在为固定大小，如同《玛祖拉的面具》和 OoT3D。使炸弹鼠" },
    { "Explosives", "炸药" },
    { "Extend certain credits scenes so the music lines up properly with the visuals. (PAL only)", "延长某些过场字幕场景，使音乐与画面正确对齐。（仅 PAL）" },
    { "Extends how far a point light can remain an object's key light, as a ", "扩展点光源能保持为物体主光源的距离，作为" },
    { "F5 to save, F6 to change slots, F7 to load", "F5 保存，F6 切换槽位，F7 加载" },
    { "Fall Damage Multiplier", "坠落伤害倍数" },
    { "Fanfare Volume: %d %%", "Fanfare 音量：%d %%" },
    { "Fast Chests", "快速宝箱" },
    { "Fast Ocarina Playback", "快速陶笛演奏" },
    { "Faster + Longer Jump", "更快 + 更远跳跃" },
    { "Faster Farore's Wind", "更快的法拉薇之风" },
    { "Faster Heavy Block Lift", "更快举起重块" },
    { "Faster Pause Menu", "更快的暂停菜单" },
    { "Faster Run", "更快奔跑" },
    { "Faster Rupee Accumulator", "更快的卢比累积器" },
    { "Faster Shadow Ship", "更快的暗影船" },
    { "File Select", "文件选择" },
    { "Fireproof Deku Shield", "防火代库盾" },
    { "Fish don't Despawn", "鱼不消失" },
    { "Fish never Escape", "鱼永不逃脱" },
    { "Fish while Hovering", "悬停时钓鱼" },
    { "Fisherman asks if you want to quit at the door if you try to leave the Fishing Pond ", "若你试图离开钓鱼池，渔夫会在门口询问是否退出" },
    { "Fishing", "钓鱼" },
    { "Fix Anubis Fireballs", "修复阿努比斯火球" },
    { "Fix Broken Giant's Knife Bug", "修复损坏的巨人之刀错误" },
    { "Fix Bush Item Drops", "修复灌木物品掉落" },
    { "Fix Camera Drift", "修复相机漂移" },
    { "Fix Camera Swing", "修复相机摆动" },
    { "Fix Credits Timing (PAL)", "修复过场字幕计时（PAL）" },
    { "Fix Dampé Going Backwards", "修复达姆佩倒退" },
    { "Fix Darunia Dancing too Fast", "修复达鲁尼亚跳舞过快" },
    { "Fix Deku Nut Upgrade", "修复代库坚果升级" },
    { "Fix Dungeon Entrances", "修复地牢入口" },
    { "Fix Enemies not Spawning Near Water", "修复敌人不在水边生成" },
    { "Fix Falling from Vine Edges", "修复从藤蔓边缘掉落" },
    { "Fix Gerudo Warrior's Clothing Colors", "修复格鲁德战士衣服颜色" },
    { "Fix Goron City Doors After Fire Temple", "修复火之神殿后的哥隆城门" },
    { "Fix Hand Holding Hammer", "修复手持锤子" },
    { "Fix Hanging Ledge Swing Rate", "修复悬挂壁架摆动速率" },
    { "Fix Kokiri Forest Quest State", "修复科克里森林任务状态" },
    { "Fix L&R Pause Menu", "修复暂停菜单的 L&R" },
    { "Fix L&Z Page Switch in Pause Menu", "修复暂停菜单中的 L&Z 页面切换" },
    { "Fix Link's Eyes Open while Sleeping", "修复林克睡觉时睁眼" },
    { "Fix Megaton Hammer Crouch Stab", "修复兆吨锤蹲刺" },
    { "Fix Missing Jingle after 5 Silver Rupees", "修复 5 枚银卢比后缺少铃声" },
    { "Fix Navi Text HUD Position", "修复娜薇文本 HUD 位置" },
    { "Fix Out of Bounds Textures", "修复越界纹理" },
    { "Fix Poacher's Saw Softlock", "修复偷猎者锯子软锁" },
    { "Fix Raised Floor Switches", "修复抬升地板开关" },
    { "Fix Two-Handed Idle Animations", "修复双手闲置动画" },
    { "Fix Vanishing Paths", "修复消失的路径" },
    { "Fix Zora Hint Dialogue", "修复佐拉提示对话" },
    { "Fix the Gravedigging Tour Glitch", "修复掘墓之旅故障" },
    { "Fixes Adult Link having a backwards Left hand when holding the Megaton Hammer.", "修复成人林克持兆吨锤时左手朝后。" },
    { "Fixes Dampé going backwards in certain circumstances when the player is going backwards.", "修复玩家倒退时达姆佩在某些情况倒退。" },
    { "Fixes Darunia's dancing speed so he dances to the beat of Saria's Song, like in the Original Game.", "修复达鲁尼亚的跳舞速度，使其随萨莉亚之歌的节拍跳舞，如同原版游戏。" },
    { "Fixes Link's eyes being open in the opening cutscene when he is supposed to be sleeping.", "修复林克在开场过场动画中本应睡着却睁眼。" },
    { "Fixes a bug where the Gravedigging Tour Heart Piece disappears if the area reloads.", "修复掘墓之旅心之碎片在区域重新加载时消失的错误。" },
    { "Fixes authentic out of bounds texture reads, instead loading textures with the correct size.", "修复原版越界纹理读取，改为以正确大小加载纹理。" },
    { "Fixes camera getting stuck on collision when standing still. Also fixes slight shift ", "修复站立不动时相机卡在碰撞上的问题。同时修复轻微移动" },
    { "Fixes camera slightly drifting to the left when standing still due to a ", "修复站立不动时相机轻微向左漂移，源于" },
    { "Fixes camera swing rate when the player falls off a ledge and the camera ", "修复玩家从壁架掉落时相机摆动速率" },
    { "Fixes kokiri animation state to match their text state when getting ", "修复科克里动画状态以匹配其文本状态" },
    { "Fixes one Zora's dialogue giving a hint about bringing Ruto's Letter to King Zora to properly occur ", "修复某佐拉对话中关于带露托的信给佐拉王的提示未能正确触发的错误" },
    { "Fixes the Broken Giant's Knife flag not being reset when Medigoron fixes it.", "修复巨人之刀损坏标志在梅迪戈隆修复时未重置。" },
    { "Fixes the bushes to drop items correctly rather than spawning undefined items.", "修复灌木以正确掉落物品，而非生成未定义物品。" },
    { "Fixes the two raised floor switches, the one in Forest Temple Basement and the one at the top of Fire ", "修复两个抬升地板开关，森林神殿地下室和火之神殿顶部" },
    { "Flicker Speed", "闪烁速度" },
    { "Font Scale: %.2fx", "字体缩放：%.2f 倍" },
    { "Foolish (16x)", "愚蠢（16x）" },
    { "Force aspect ratio:", "强制宽高比：" },
    { "Forces Goron City doors open if you somehow complete Fire Temple without talking to Goron Link ", "若你以某种方式完成火之神殿而未与哥隆林克对话，强制打开哥隆城门" },
    { "Forces the rupee order to not be randomized as adult, making it the same as child.", "强制卢比顺序在成人时不随机化，使其与儿童相同。" },
    { "Forest Temple", "森林神殿" },
    { "Frame Advance", "逐帧前进" },
    { "Freeze Time", "冻结时间" },
    { "Freeze Traps", "冻结陷阱" },
    { "Freezes the time of day.", "冻结一天中的时间。" },
    { "French", "法语" },
    { "Frogs' Ocarina Game", "青蛙的陶笛游戏" },
    { "Gameplay Fixes", "游戏玩法修复" },
    { "General", "通用" },
    { "General Settings", "通用设置" },
    { "Generate Randomizer", "生成随机化器" },
    { "Generates a random color value to use", "生成要使用的随机颜色值" },
    { "German", "德语" },
    { "Ghost Pepper", "鬼椒" },
    { "Gives you the glitched damage value of the quick put away glitch.", "给予你快速收起故障的错误伤害值。" },
    { "Glitch Aids", "故障辅助" },
    { "Glitch Line-up Tick", "故障对齐刻度" },
    { "Glitch Restorations", "故障还原" },
    { "Gold Skulltula Tokens", "黄金骷髅代币" },
    { "Gradient Brightness", "渐变亮度" },
    { "Graphical Fixes", "图形修复" },
    { "Graphical Restorations", "图形还原" },
    { "Graphics", "图形" },
    { "Graphics Options", "图形选项" },
    { "Grave Hole Jumps", "坟墓洞跳跃" },
    { "Gray", "灰色" },
    { "Greatly decreases cast time of Farore's Wind magic spell.", "大幅减少法拉薇之风魔法的施法时间。" },
    { "Green", "绿色" },
    { "Guarantee Bite", "保证咬钩" },
    { "Habanero", "哈瓦那椒" },
    { "Health", "生命" },
    { "Heart Containers", "心之容器" },
    { "Helps FW persist between ages, gives Child and Adult separate FW points, and can ", "帮助法拉薇之风在年龄间持续，为儿童和成人提供独立的 FW 点，并可" },
    { "Hidden", "隐藏" },
    { "Hide Background", "隐藏背景" },
    { "Hide Vanilla Torch Glow", "隐藏原版火把光晕" },
    { "Hide the original game's actor shadows (Link's feet, the NPC/enemy circles, the horse shadow, ", "隐藏原版游戏的角色阴影（林克的脚、NPC/敌人圆圈、马影、" },
    { "Hides most of the UI when not needed.\n", "在不需要时隐藏大部分 UI。\n" },
    { "Hides the original flat, billboarded, flickering glow circle the game draws over torches and ", "隐藏游戏在火把和精灵上方绘制的原版扁平、广告牌式闪烁光晕圈" },
    { "Highlight Intensity", "高光强度" },
    { "Highlight Lit Objects", "高亮受光物体" },
    { "Holding L makes you float into the air.", "按住 L 让你漂浮到空中。" },
    { "Holding down B skips text.", "按住 B 跳过文本。" },
    { "Hookshot", "钩爪" },
    { "Hookshot Everything", "一切皆可钩" },
    { "Hookshot Reach Multiplier: %.2fx", "钩爪触及倍数：%.2f 倍" },
    { "Horizon", "地平线" },
    { "Horizon Height", "地平线高度" },
    { "Horizon Parallax", "地平线视差" },
    { "Host & Port", "主机与端口" },
    { "How dark the shadow side gets. 0% = no shadow (flat), 100% = full ", "阴影面有多暗。0% = 无阴影（平面），100% = 完全" },
    { "How dark the shadow's core is. 0 = invisible; higher = darker.", "阴影核心有多暗。0 = 不可见；越高 = 越暗。" },
    { "How far ABOVE the feet the shadow can climb onto rising ground. Raise this so the ", "阴影能爬上上升地面的脚部上方距离。提高此值以使" },
    { "How far below the feet the shadow conforms to the ground. The shadow is a thin ", "阴影贴合地面的脚部下方距离。阴影是一层薄" },
    { "How fast the clouds drift across the sky on the wind. 1x is Wind Waker's ", "云在风中漂移的速度。1x 为风之杖的" },
    { "How fast the stars pulse. 1x is Wind Waker's rate — about ten seconds per ", "星星脉动的速度。1x 为风之杖的速率——约每十秒" },
    { "How fast the wisps fly. 1x is Wind Waker's own speed. The whole flight ", "风精飞行的速度。1x 为风之杖自身速度。整个飞行" },
    { "How large notifications are.", "通知的大小。" },
    { "How long notifications are displayed for.", "通知显示的时间。" },
    { "How long the key light takes to ease from one source to another. Higher ", "主光源从一个来源缓动到另一个来源所需时间。越高" },
    { "How long the shadow may get. The key light is raised toward straight-overhead ", "阴影可能达到的长度。主光源被抬升到接近正上方" },
    { "How many wisps ride the wind (their number also rises and falls with the ", "有多少风精乘风而行（其数量也随" },
    { "How much of the sky the clouds fill — from a few scattered clouds up to ", "云填满天空的多少——从零星散布的云到" },
    { "How much the sky horizon sinks as the camera climbs. 0% = it follows the ", "随着相机攀升，天空地平线下沉多少。0% = 跟随" },
    { "How often flames pick a new brightness for the Wind Waker flicker. Higher = ", "火焰为风之杖闪烁选择新亮度的频率。越高 =" },
    { "How opaque the background of notifications is.", "通知背景的不透明度。" },
    { "How opaque the clouds are.", "云的不透明度。" },
    { "Hurt Container Mode", "受伤容器模式" },
    { "Hyper Bosses", "超级 Boss" },
    { "Hyper Enemies", "超级敌人" },
    { "I promise I have read the warning", "我承诺已阅读警告" },
    { "I understand, enable save states", "我理解，启用存档状态" },
    { "If enabled, signs near loading zones will tell you where they lead to.", "若启用，加载区附近的标志将告诉你它们通向何处。" },
    { "ImGui Menu Scaling", "ImGui 菜单缩放" },
    { "Improve Flame Flicker", "改善火焰闪烁" },
    { "Include Held Inputs at the Start of Pause Buffer Input Window", "在暂停缓冲输入窗口起始包含按住的输入" },
    { "Increase Actor Draw Distance: %dx", "增加角色绘制距离：%d 倍" },
    { "Increases the range in which Actors/Objects are drawn.", "增加角色/物体绘制的范围。" },
    { "Indigo", "靛蓝" },
    { "Infinite...", "无限……" },
    { "Info", "信息" },
    { "Ingame Text Spacing: %d", "游戏内文本间距：%d" },
    { "Input Viewer", "输入查看器" },
    { "Input Viewer Settings", "输入查看器设置" },
    { "Instant Age Change", "瞬间改变年龄" },
    { "Instant Boomerang Recall", "瞬间召回回旋镖" },
    { "Instant Fishing", "瞬间钓鱼" },
    { "Instant Putaway", "瞬间收起" },
    { "Instant Win", "瞬间胜利" },
    { "Instant Win##Frogs", "瞬间胜利##Frogs" },
    { "Instant Win##LostWoods", "瞬间胜利##LostWoods" },
    { "Instantly return the Boomerang to Link by pressing its item button while ", "在按住回旋镖物品按钮时立即将其召回林克" },
    { "Integer scales the image. Only available in Pixel Perfect Mode.", "整数缩放图像。仅在像素完美模式下可用。" },
    { "Interface Language", "界面语言" },
    { "Internal Resolution", "内部分辨率" },
    { "Internal resolution: {} x {}", "内部分辨率：{} x {}" },
    { "Interval between Rupee reduction in Rupee Dash Mode.", "卢比冲刺模式中卢比减少的间隔。" },
    { "Introduces Options for unequipping Link's sword\n\n", "引入卸下林克之剑的选项\n\n" },
    { "Invisible Bunny Hood", "隐形兔帽" },
    { "Item Count Messages", "物品数量消息" },
    { "Item Scale: %.2f", "物品缩放：%.2f" },
    { "Item Tracker", "物品追踪器" },
    { "Item Tracker Settings", "物品追踪器设置" },
    { "Item-related Fixes", "物品相关修复" },
    { "Items", "物品" },
    { "Ivan the Fairy (Coop Mode)", "精灵伊万（合作模式）" },
    { "Jabber Nut Colors Match Kind", "喋喋坚果颜色匹配种类" },
    { "Jalapeño", "墨西哥辣椒" },
    { "Japanese", "日语" },
    { "Junk Items", "垃圾物品" },
    { "Keese and Guay no longer target you and simply ignore you as if you were wearing the ", "吉斯和瓜伊不再瞄准你，而是像你戴着" },
    { "Keese/Guay don't Target You", "吉斯/瓜伊不瞄准你" },
    { "King Zora Speed: %.2fx", "佐拉王速度：%.2f 倍" },
    { "Knockback Traps", "击退陷阱" },
    { "Language", "语言" },
    { "Languages", "语言" },
    { "Large", "大" },
    { "Leever Spawn Rate: %d seconds", "利弗生成速率：%d 秒" },
    { "Length", "长度" },
    { "Let Navi count as a candidate key light for cel shading. Navi blinks on/off and orbits Link, so ", "让娜薇作为卡通渲染的候选主光源。娜薇闪烁并环绕林克，所以" },
    { "Let shadows fall on a few \"floors\" that the game spawns as actors instead of room geometry — the ", "让阴影落在游戏作为角色生成的几个“地板”上——而非房间几何体" },
    { "Light Blue", "浅蓝" },
    { "Light Casting", "光投射" },
    { "Light Source Viewer", "光源查看器" },
    { "Lights", "光源" },
    { "Linear", "线性" },
    { "Link as Default File Name", "林克作为默认文件名" },
    { "Link will not spin when the Goron Pot starts to spin.", "当哥隆壶开始旋转时林克不会旋转。" },
    { "Link's Cow in Both Time Periods", "林克的牛在两个时间段" },
    { "Loaches always Appear", "泥鳅总是出现" },
    { "Loaches will always appear in the fishing pond instead of every four visits.", "泥鳅将始终出现在钓鱼池中，而非每四次访问出现一次。" },
    { "Lock", "锁定" },
    { "Log Level", "日志级别" },
    { "Logs some resources as XML when they're loaded in binary format.", "当资源以二进制格式加载时，将其记录为 XML。" },
    { "Lost Woods Ocarina Game", "迷失森林陶笛游戏" },
    { "Magic", "魔法" },
    { "Magic Spells", "魔法咒语" },
    { "Main Music Volume: %d %%", "主音乐音量：%d %%" },
    { "Make Anubis Fireballs do Fire damage when reflected back at them with the Mirror Shield.", "用镜像盾反射时，使阿努比斯火球造成火焰伤害。" },
    { "Make Deku Nuts explode Bombs, similar to how they interact with Bombchus. ", "让代库坚果引爆炸弹，类似于它们与炸弹鼠的互动。" },
    { "Make crouch stabbing always do the same damage as a regular slash.", "使蹲刺始终造成与普通挥砍相同的伤害。" },
    { "Make the Megaton Hammer's crouch stab able to destroy rocks without first swinging it normally.", "使兆吨锤的蹲刺能在不先正常挥舞的情况下摧毁岩石。" },
    { "Makes Dampe appear anytime during the night, not just his usual working hours.", "使达姆佩在夜间任何时间出现，而非仅在其正常工作时间。" },
    { "Makes Gold Skulltulas come out of bean patches faster after bugs dig into center.", "使黄金骷髅更快从豆荚中钻出。" },
    { "Makes L and R switch pages like on the GameCube. Z opens the Debug Menu instead.", "使 L 和 R 像 GameCube 上一样切换页面。Z 改为打开调试菜单。" },
    { "Makes Link always kick the chest to open it, instead of doing the longer ", "使林克总是踢开宝箱来打开它，而非做更长的" },
    { "Makes a lit, held Deku stick a real light source at its burning tip (it isn't in vanilla). Like a ", "使点燃的、手持的代库木棒在其燃烧尖端成为真实光源（原版中不是）。像" },
    { "Makes all equipment visible, regardless of age.", "使所有装备可见，不受年龄限制。" },
    { "Makes every surface in the game climbable.", "使游戏中所有表面都可攀爬。" },
    { "Makes every surface in the game hookshotable.", "使游戏中所有表面都可钩。" },
    { "Makes every tunic have the effects of every other tunic.", "使每件外衣都具有其他外衣的效果。" },
    { "Makes non-Navi fairies emit light (they don't in vanilla): the fairies that drift around places ", "使非娜薇精灵发光（原版中不会）：在各地飘荡的精灵" },
    { "Makes the Hookshot Reticle use a different color when aiming at hookshotable collision.", "使钩爪准星在瞄准可钩碰撞时使用不同颜色。" },
    { "Makes the L and R buttons in the pause menu the same color.", "使暂停菜单中的 L 和 R 按钮颜色相同。" },
    { "Makes the cursor always visible, even in full screen.", "使光标始终可见，即使在全屏下。" },
    { "Manual seed entry", "手动种子输入" },
    { "Map & Compass Colors Match Dungeon", "地图与罗盘颜色匹配地牢" },
    { "Map Select Button Combination:", "地图选择按钮组合：" },
    { "Mask Select in Inventory", "物品栏中的面具选择" },
    { "Masks", "面具" },
    { "Masks Equippable as Adult", "成人为可装备面具" },
    { "Master Volume: %d %%", "主音量：%d %%" },
    { "Match Refresh Rate", "匹配刷新率" },
    { "Matches interpolation value to the refresh rate of your display.", "将插值值与显示器的刷新率匹配。" },
    { "Matches the color of maps & compasses to the dungeon they belong to. ", "将地图与罗盘的颜色匹配到它们所属的地牢。" },
    { "Maxed", "已满" },
    { "Maximum number of stars at full night (the visible count rises and falls ", "满夜时的最大星星数（可见数量随" },
    { "Menu Background Opacity", "菜单背景不透明度" },
    { "Menu Controller Navigation", "菜单控制器导航" },
    { "Menu Settings", "菜单设置" },
    { "Menu Theme", "菜单主题" },
    { "Merciless (64x)", "无情（64x）" },
    { "Metal", "金属" },
    { "Minimal UI", "极简 UI" },
    { "Mirrored World", "镜像世界" },
    { "Mirrors the world horizontally:\n\n", "水平镜像世界：\n\n" },
    { "Misc", "杂项" },
    { "Misc Restorations", "杂项还原" },
    { "Misc.", "杂项。" },
    { "Miscellaneous", "杂项" },
    { "Models & Textures", "模型与纹理" },
    { "Modifies Damage taken after Bonking.", "修改撞击后受到的伤害。" },
    { "Modifies all fall damage:\n", "修改所有坠落伤害：\n" },
    { "Modifies all sources of damage not affected by other sliders:\n", "修改不受其他滑块影响的所有伤害来源：\n" },
    { "Modifies damage taken after falling into a void:\n", "修改坠入虚空后受到的伤害：\n" },
    { "Modify Note Timer: %dx", "修改音符计时器：%d 倍" },
    { "Mods", "模组" },
    { "Money", "金钱" },
    { "Moon Jump on L", "按 L 月步跳" },
    { "More Info in File Select", "文件选择中更多信息" },
    { "MoreResolutionSettings", "更多分辨率设置" },
    { "Multiplier:", "倍数：" },
    { "Multiplies your output resolution by the value inputted, as a more intensive but effective ", "将输出分辨率乘以输入的值，作为一种更密集但有效的" },
    { "Mute Notification Sound", "静音通知声音" },
    { "Mysterious Shuffled Items", "神秘的洗牌物品" },
    { "N64 Mode", "N64 模式" },
    { "N64 Weird Frames", "N64 怪异帧" },
    { "NPCs", "NPC" },
    { "Navi", "娜薇" },
    { "Navi Timer Resets on Scene Change", "场景切换时重置娜薇计时器" },
    { "Navi's Light Tint", "娜薇的色调" },
    { "Nayru's Love", "娜茹之爱" },
    { "Network", "网络" },
    { "Never", "从不" },
    { "Nighttime GS Always Spawn", "夜间黄金骷髅总是生成" },
    { "Nighttime Skulltulas will spawn during both day and night.", "夜间黄金骷髅在白天和夜晚都会生成。" },
    { "Nintendo 3DS (5:3)", "任天堂 3DS (5:3)" },
    { "No Clip", "穿墙" },
    { "No Clip Button Combination:", "穿墙按钮组合：" },
    { "No Damage", "无伤害" },
    { "No Heart Drops", "无心形掉落" },
    { "No Random Drops", "无随机掉落" },
    { "No ReDead/Gibdo Freeze", "无 ReDead/吉布多冻结" },
    { "No Rupee Randomization", "无卢比随机化" },
    { "No Skulltula Freeze", "无黄金骷髅冻结" },
    { "No Vanish", "无消失" },
    { "None", "无" },
    { "None##Skips", "无##Skips" },
    { "Normal", "普通" },
    { "Note Play Speed: %dx", "音符演奏速度：%d 倍" },
    { "Notification on Autosave", "自动保存时通知" },
    { "Null", "空" },
    { "Number of Starting Notes: %d notes", "起始音符数：%d 个音符" },
    { "OHKO", "一击必杀" },
    { "OHKO (256x)", "一击必杀（256x）" },
    { "Ocarina", "陶笛" },
    { "Ocarina of Time", "时之陶笛" },
    { "Ocarina of Time + Master Sword", "时之陶笛 + 大师之剑" },
    { "Octuple (8x)", "八倍（8x）" },
    { "Off", "关闭" },
    { "Once", "一次" },
    { "Once a hook as been set, Fish will never let go while being reeled in.", "一旦设下钩，鱼在被收线时永远不会松口。" },
    { "Only change the texture of containers if you have the Stone of Agony.", "仅在你拥有痛苦之石时更改容器的纹理。" },
    { "Only in Rando", "仅在随机化中" },
    { "OoT Registry Editor", "OoT 注册表编辑器" },
    { "OoT Skulltula Debug", "OoT 黄金骷髅调试" },
    { "Opacity", "不透明度" },
    { "Open App Files Folder", "打开应用文件文件夹" },
    { "OpenGL", "OpenGL" },
    { "Opens the folder that contains the save and mods folders, etc.", "打开包含存档和模组文件夹等的文件夹。" },
    { "Optimized Debug Warp Screen, with the added ability to chose entrances and time of day.", "优化的调试传送屏幕，增加了选择入口和一天中时间的能力。" },
    { "Options", "选项" },
    { "Orange", "橙色" },
    { "Original (4:3)", "原始（4:3）" },
    { "Overall brightness of the sky gradient. Raise for a more vivid sky, lower ", "天空渐变的整体亮度。提高以获得更生动的天空，降低" },
    { "Overall star brightness. Higher = brighter, more prominent stars.", "星星的整体亮度。越高 = 越亮、越显眼的星星。" },
    { "Overlays a translucent faceted shell of each light's icosphere — the volume used for its cast ", "叠加每个光源的二十面球体的半透明刻面外壳——用于投射的" },
    { "Override the resolution scale slider and use the settings below, irrespective of window size.", "覆盖分辨率缩放滑块并使用以下设置，无论窗口大小。" },
    { "Passive Infinite Sword Glitch\n", "被动无限剑术故障\n" },
    { "Pause Buffer Input Window: %d frames", "暂停缓冲输入窗口：%d 帧" },
    { "Pause Menu", "暂停菜单" },
    { "Pause Warp", "暂停传送" },
    { "Performance: actors farther than this from the camera get no shape shadow (each ", "性能：距离相机超过此值的角色没有形状阴影（每个" },
    { "Permanent Heart Loss", "永久失去心" },
    { "Persistent Masks", "持久面具" },
    { "Pieces of Heart", "心之碎片" },
    { "Pierre appears when an Ocarina is pulled out. Requires learning the Scarecrow's Song first.\n", "当拔出陶笛时皮埃尔出现。需先学会稻草人之歌。\n" },
    { "Pins the pool's tumble and size pulse to the authentic Wind Waker rates. Turn off to reveal and ", "将光池的翻滚和尺寸脉动固定为原版风之杖速率。关闭以显示和" },
    { "Play Zelda's Lullaby to Open Sleeping Waterfall", "演奏塞尔达的摇篮曲打开沉睡瀑布" },
    { "Play unique fanfares when obtaining quest items (medallions/stones/songs). Note that these ", "获得任务物品（勋章/石头/歌曲）时播放独特的 fanfare。注意这些" },
    { "Point Light Range", "点光源范围" },
    { "Popout Actor Viewer", "弹出角色查看器" },
    { "Popout Audio Editor Window", "弹出音频编辑器窗口" },
    { "Popout Bindings Window", "弹出按键绑定窗口" },
    { "Popout Check Tracker Settings", "弹出检查追踪器设置" },
    { "Popout Collision Viewer", "弹出碰撞查看器" },
    { "Popout Console", "弹出控制台" },
    { "Popout Cosmetics Editor Window", "弹出化妆编辑器窗口" },
    { "Popout Display List Viewer", "弹出显示列表查看器" },
    { "Popout Entrance Tracker Settings", "弹出入口追踪器设置" },
    { "Popout Gameplay Stats Window", "弹出游戏统计窗口" },
    { "Popout Gfx Debugger", "弹出图形调试器" },
    { "Popout Hook Debugger", "弹出钩子调试器" },
    { "Popout Input Viewer Settings", "弹出输入查看器设置" },
    { "Popout Item Tracker Settings", "弹出物品追踪器设置" },
    { "Popout Menu", "弹出菜单" },
    { "Popout Message Viewer", "弹出消息查看器" },
    { "Popout Mod Menu Window", "弹出模组菜单窗口" },
    { "Popout Plandomizer Window", "弹出计划随机化器窗口" },
    { "Popout Save Editor", "弹出存档编辑器" },
    { "Popout Stats Window", "弹出统计窗口" },
    { "Popout Time Splits Window", "弹出时间分段窗口" },
    { "Popout Value Viewer", "弹出数值查看器" },
    { "Position", "位置" },
    { "Preserve the minimap visibility state when going between areas rather than default it to \"on\" ", "在区域间移动时保留小地图可见状态，而非默认设为“开”" },
    { "Prevent Bombchus Forcing First-Person", "防止炸弹鼠强制第一人称" },
    { "Prevent Bombchus from forcing the camera into first-person mode when released.", "防止炸弹鼠在释放时强制相机进入第一人称模式。" },
    { "Prevent Dropped Ocarina Inputs", "防止丢弃的陶笛输入" },
    { "Prevent dropping inputs when playing the Ocarina too quickly.", "防止演奏陶笛过快时丢弃输入。" },
    { "Prevent forced conversations with Navi and/or other NPCs.", "防止与娜薇和/或其他 NPC 的强制对话。" },
    { "Prevent notifications from playing a sound.", "防止通知播放声音。" },
    { "Prevent the Gerudo Warrior's clothes changing color when changing Link's tunic or ", "防止格鲁德战士的衣服在更换林克外衣或" },
    { "Prevents ReDeads and Gibdos from being able to freeze you with their scream.", "防止 ReDead 和吉布多用尖叫冻结你。" },
    { "Prevents bugs from automatically despawning after a while when dropped.", "防止虫子掉落一段时间后自动消失。" },
    { "Prevents fish from automatically despawning after a while when dropped.", "防止鱼掉落一段时间后自动消失。" },
    { "Prevents immediately falling off climbable surfaces if climbing on the edges.", "防止在边缘攀爬时立即从可攀爬表面掉落。" },
    { "Prevents integer scaling factor from exceeding screen bounds.\n\n", "防止整数缩放因子超出屏幕边界。\n\n" },
    { "Prevents the Deku Shield from burning on contact with fire.", "防止代库盾接触火时燃烧。" },
    { "Prevents the Forest Stage Deku Nut upgrade from becoming unobtainable ", "防止森林舞台代库坚果升级变得无法获得" },
    { "Prevents the Poacher's Saw softlock from mashing through the text, or with Skip Text enabled.", "防止偷猎者锯子软锁通过连按文本或启用跳过文本触发。" },
    { "Prevents the big Cucco from appearing in the Bombchu Bowling minigame.", "防止大公鸡出现在炸弹鼠保龄球小游戏。" },
    { "Prevents the small Cucco from appearing in the Bombchu Bowling minigame.", "防止小公鸡出现在炸弹鼠保龄球小游戏。" },
    { "Prevents this color from being changed", "防止此颜色被更改" },
    { "Pull Grave During the Day", "白天拉坟墓" },
    { "Pulsate Boss Icon", "脉动 Boss 图标" },
    { "PulseAudio", "PulseAudio" },
    { "Pure Torture (128x)", "纯粹折磨（128x）" },
    { "Purple", "紫色" },
    { "Quadruple (4x)", "四倍（4x）" },
    { "Quest Item Fanfares", "任务物品 Fanfare" },
    { "Quick Bongo Kill", "快速邦戈击杀" },
    { "Quick Boss Deaths", "快速 Boss 死亡" },
    { "Quick Putaway", "快速收起" },
    { "Quit", "退出" },
    { "Quit Fishing at Door", "在门口退出钓鱼" },
    { "Quit SoH", "退出 SoH" },
    { "Rainbow", "彩虹" },
    { "Raises or lowers the sky's horizon line — the gradient's haze boundary and ", "升高或降低天空的地平线——渐变朦胧边界和" },
    { "Ramp Center", "斜坡中心" },
    { "Ramp Softness", "斜坡柔和度" },
    { "Rando-Relevant Navi Hints", "随机化相关娜薇提示" },
    { "Random", "随机" },
    { "Random (Seeded)", "随机（种子）" },
    { "Random Rupee Names", "随机卢比名称" },
    { "Randomizer", "随机化器" },
    { "Re-Enables the two-handed idle animation, a seemingly finished animation that was disabled on accident ", "重新启用双手闲置动画，一个看似完成却意外禁用的动画" },
    { "Re-lights actors and objects with a single dominant light and a soft Wind Waker-style ramp. ", "用单一主光源和柔和的风之杖风格斜坡重新照亮角色和物体。" },
    { "Rebottle Blue Fire", "重新装瓶蓝火" },
    { "Red", "红色" },
    { "Red Ganon Blood", "红色加农血液" },
    { "Remember Minimap State Between Areas", "在区域间记住小地图状态" },
    { "Remember Save Location", "记住存档位置" },
    { "Remote Bombchu", "远程炸弹鼠" },
    { "Remove Big Cucco", "移除大公鸡" },
    { "Remove Explosive Limit", "移除炸药限制" },
    { "Remove Power Crouch Stab", "移除强力蹲刺" },
    { "Remove Small Cucco", "移除小公鸡" },
    { "Remove Spin Attack Darkness", "移除旋转攻击黑暗" },
    { "Remove the Darkness that appears when charging a Spin Attack.", "移除蓄力旋转攻击时出现的黑暗。" },
    { "Remove this button from the combination", "从组合中移除此按钮" },
    { "Removes tearing, but clamps your max FPS to your displays refresh rate.", "消除画面撕裂，但将最大 FPS 限制为显示器刷新率。" },
    { "Removes the Dungeon Entrance icon on the top-left corner of the screen when no dungeon is present on the ", "移除屏幕左上角的地牢入口图标（当该区域没有地牢时）。" },
    { "Removes the Input Requirement on Text boxes after defeating Ganon, allowing the Credits ", "移除击败加农后文本框的输入要求，允许过场字幕" },
    { "Removes the cap of 3 active explosives being deployed at once.", "移除同时部署 3 个活跃炸药的 cap。" },
    { "Removes the timer to play back the song.", "移除演奏歌曲的计时器。" },
    { "Render Distance: %d", "渲染距离：%d" },
    { "Renderer API (Needs reload)", "渲染器 API（需重新加载）" },
    { "Renders Gauntlets when using the Bow and Hookshot like in OoT3D.", "像 OoT3D 中一样，在使用弓和钩爪时渲染臂铠。" },
    { "Renders a health bar for Enemies when Z-Targeted.", "在 Z 瞄准时为敌人渲染生命条。" },
    { "Renders every cel-shaded object as flat white on the lit side and flat black in shadow (the ", "将每个卡通渲染物体渲染为受光面纯白、阴影中纯黑（" },
    { "Replace Navi's overworld quest hints with rando-related gameplay hints.", "用随机化相关的游戏玩法提示替换娜薇的地面任务提示。" },
    { "Replace Sky Texture", "替换天空纹理" },
    { "Replaces most 2D items and projectiles on the overworld with their equivalent 3D models.", "用等效的 3D 模型替换地面上的大多数 2D 物品和抛射物。" },
    { "Replaces the game's fast, jagged per-frame torch/flame flicker with a slow, organic Wind Waker ", "将游戏快速、锯齿状的逐帧火把/火焰闪烁替换为缓慢、自然的风之杖" },
    { "Replaces the overworld sky with a Wind Waker-style one: a gradient sky dome, drifting puffy ", "用风之杖风格的天空替换地面天空：渐变穹顶、飘逸蓬松" },
    { "Replaces the sky texture with a smooth Wind Waker-style gradient, fading from a hazy horizon ", "用平滑的风之杖风格渐变替换天空纹理，从朦胧的地平线" },
    { "Replaces the vanilla actor shadows with a shape-based drop shadow for each actor (Link, NPCs, ", "用基于形状的下落阴影替换原版角色阴影，为每个角色（林克、NPC、" },
    { "Reset", "重置" },
    { "Reset All to Defaults", "全部重置为默认" },
    { "Reset Button Combination:", "重置按钮组合：" },
    { "Resets all the Actor Shadows sliders below to their default values.", "将下方所有角色阴影滑块重置为默认值。" },
    { "Resets all the Cel Shading sliders below to their default values.", "将下方所有卡通渲染滑块重置为默认值。" },
    { "Resets the Navi timer on scene change. If you have already talked to her, ", "在场景切换时重置娜薇计时器。如果你已经和她交谈过，" },
    { "Resets this color to its default value", "将此颜色重置为默认值" },
    { "Resource logging", "资源日志" },
    { "Respawn with Full Health instead of 3 hearts.", "以满生命重生，而非 3 颗心。" },
    { "Restore Old Gold Skulltula Cutscene", "还原旧版黄金骷髅过场动画" },
    { "Restore a bug from NTSC 1.0 that allows bypassing Bongo Bongo's intro cutscene to quickly kill him.", "还原 NTSC 1.0 中的错误，允许跳过邦戈邦戈的入场过场动画以快速击杀他。" },
    { "Restore a bug from NTSC 1.0 that allows casting the Fishing Rod while using the Hover Boots.", "还原 NTSC 1.0 中的错误，允许在使用悬浮靴时投掷钓鱼竿。" },
    { "Restore a bug from NTSC 1.0 that allows putting away an item without an animation and performing ", "还原 NTSC 1.0 中的错误，允许无动画收起物品并执行" },
    { "Restore pre-release behavior where defeating a Gold Skulltula will play a cutscene showing it die.", "还原发布前的行为，击败黄金骷髅时会播放其死亡的过场动画。" },
    { "Restore the original red blood from NTSC 1.0/1.1. Disable for Green blood.", "还原 NTSC 1.0/1.1 中的原版红色血液。禁用则为绿色血液。" },
    { "Restores N64 Weird Frames allowing weirdshots and weirdslides to behave the same as N64.", "还原 N64 怪异帧，使怪异截图和怪异滑行与 N64 表现相同。" },
    { "Restores NTSC 1.0 behavior where Link jumps over grave holes and grabs the ledges.", "还原 NTSC 1.0 中林克跳过坟墓洞并抓住壁架的行为。" },
    { "Restores a bug from NTSC 1.0/1.1 that allows you to obtain the eyeball frog from King Zora ", "还原 NTSC 1.0/1.1 中的错误，允许你从佐拉王处获得眼球蛙" },
    { "Restores an unfinished feature to pulsate the boss room icon when you are in the boss room.", "还原一个未完成的功能，当你在 Boss 房间时脉动 Boss 房间图标。" },
    { "Restores the wider range of certain shutter doors from NTSC 1.0.\n", "还原 NTSC 1.0 中某些卷帘门的更宽范围。\n" },
    { "Reworked Targeting", "重做的瞄准" },
    { "Reworks targeting functionality\n", "重做瞄准功能\n" },
    { "Ridiculous (32x)", "荒谬（32x）" },
    { "Rotation Speed", "旋转速度" },
    { "Round One Notes: %d notes", "第一轮音符：%d 个音符" },
    { "Round Three Notes: %d notes", "第三轮音符：%d 个音符" },
    { "Round Two Notes: %d notes", "第二轮音符：%d 个音符" },
    { "Rupee Dash Interval %d seconds", "卢比冲刺间隔 %d 秒" },
    { "Rupee Dash Mode", "卢比冲刺模式" },
    { "Rupees reduce over time, Link suffers damage when the count hits 0.", "卢比随时间减少，计数归零时林克受到伤害。" },
    { "SDL", "SDL" },
    { "SDL Audio", "SDL 音频" },
    { "Sail is a networking protocol designed to facilitate remote ", "Sail 是一个旨在促进远程" },
    { "Save States", "存档状态" },
    { "Save the game automatically on a 3 minute interval and when soft-resetting the game. The interval ", "每隔 3 分钟自动保存游戏，并在软重置游戏时保存。间隔" },
    { "Saving", "保存中" },
    { "Scale Adult Equipment as Child", "以儿童身形缩放成人装备" },
    { "Scales all of the Adult Equipment, as well as moving some a bit, to fit on Child Link better. May ", "缩放所有成人装备，并稍微移动一些，以更好地贴合儿童林克。可能" },
    { "Search In Sidebar", "在侧边栏中搜索" },
    { "Search Input Autofocus", "搜索输入框自动聚焦" },
    { "Search input box gets autofocus when visible. Does not affect using other widgets.", "搜索输入框在可见时自动聚焦。不影响使用其他控件。" },
    { "Searches all menus for the given text, including tooltips.", "在所有菜单中搜索给定文本，包括工具提示。" },
    { "Seed", "种子" },
    { "Seed Entry", "种子输入" },
    { "Select the display language for the menu interface.", "选择菜单界面的显示语言。" },
    { "Selection of warp song in pause menu initiates a warp. Disables song playback.", "在暂停菜单中选择传送歌曲会发起传送。禁用歌曲演奏。" },
    { "Serrano", "塞拉诺椒" },
    { "Set the Beta Quest world to explore. *WARNING*: Changing this will reset your game!\n", "设置要探索的测试任务世界。*警告*：更改此项将重置你的游戏！\n" },
    { "Sets the applied Texture Filtering.", "设置应用的纹理过滤。" },
    { "Sets the aspect ratio to 4:3 and lowers resolution to 240p, the N64's native resolution.", "将宽高比设为 4:3 并将分辨率降至 240p，即 N64 的原生分辨率。" },
    { "Sets the audio API used by the game. Requires a relaunch to take effect.", "设置游戏使用的音频 API。需要重新启动生效。" },
    { "Sets the opacity of the background of the port menu.", "设置端口菜单背景的不透明度。" },
    { "Sets the renderer API used by the game.", "设置游戏使用的渲染器 API。" },
    { "Settings", "设置" },
    { "Shadow Intensity", "阴影强度" },
    { "Shadow Tag Mode", "阴影标签模式" },
    { "Shadows on Walkable Actors", "可行走角色上的阴影" },
    { "Shield with Two-Handed Weapons", "双手武器配盾" },
    { "Ship Of Harkinian", "哈肯尼安之船" },
    { "Shock Traps", "电击陷阱" },
    { "Shooting Gallery", "射击场" },
    { "Shops and Games Always Open", "商店和游戏始终开放" },
    { "Shops and Minigames are open both day and night. Requires a scene reload to take effect.", "商店和小游戏白天和夜晚都开放。需要场景重新加载生效。" },
    { "Show Age-Dependent Equipment", "显示随年龄变化的装备" },
    { "Show Chains on Both Sides of Locked Doors", "在锁门两侧显示锁链" },
    { "Show Gauntlets in First-Person", "在第一人称中显示臂铠" },
    { "Show Light Spheres", "显示光球" },
    { "Show Shadow Volume", "显示阴影体积" },
    { "Show a notification when the game is autosaved.", "游戏自动保存时显示通知。" },
    { "Shows what items you have collected in the File Select screen, like in N64 Randomizer.", "在文件选择屏幕显示你收集的物品，如同 N64 随机化中。" },
    { "Signs Hint Entrances", "标志提示入口" },
    { "Simpler Boss Soul Models", "更简单的 Boss 灵魂模型" },
    { "Simulated Input Lag: %d frames", "模拟输入延迟：%d 帧" },
    { "Size Flicker", "尺寸闪烁" },
    { "Size:", "尺寸：" },
    { "Skip Boss Introductions", "跳过 Boss 介绍" },
    { "Skip Bottle Pickup Messages", "跳过瓶子拾取消息" },
    { "Skip Child Stealth", "跳过儿童潜行" },
    { "Skip Consumable Item Pickup Messages", "跳过消耗品拾取消息" },
    { "Skip Entrance Cutscenes", "跳过入口过场动画" },
    { "Skip Feeding Jabu-Jabu", "跳过喂养贾布贾布" },
    { "Skip Forced Dialog", "跳过强制对话" },
    { "Skip Get Item Animations", "跳过获得物品动画" },
    { "Skip Intro", "跳过开场" },
    { "Skip Keep Confirmation", "跳过保留确认" },
    { "Skip Magic Arrow Equip Animation", "跳魔法箭装备动画" },
    { "Skip Misc Interactions", "跳过杂项互动" },
    { "Skip One Point Cutscenes (Chests, Door Unlocks, etc.)", "跳过单点过场动画（宝箱、开门等）" },
    { "Skip Owl Interactions", "跳过猫头鹰互动" },
    { "Skip Pickup Messages for Bottle Swipes.", "跳过瓶子挥动拾取消息。" },
    { "Skip Pickup Messages for new Consumable Items.", "跳过新消耗品的拾取消息。" },
    { "Skip Playing Scarecrow's Song", "跳过演奏稻草人之歌" },
    { "Skip Save Confirmation", "跳过保存确认" },
    { "Skip Song Cutscenes", "跳歌曲过场动画" },
    { "Skip Story Cutscenes", "跳过故事过场动画" },
    { "Skip Text", "跳过文本" },
    { "Skip Tower Escape", "跳过塔楼逃脱" },
    { "Skip Water Take Breath Animation", "跳过水中呼吸动画" },
    { "Skip the \"Game Saved\" confirmation screen.", "跳过“游戏已保存”确认屏幕。" },
    { "Skip the part where the Ocarina Playback is called when you play a song.", "跳过演奏歌曲时调用陶笛回放的环节。" },
    { "Skip the tower escape sequence between Ganondorf and Ganon.", "跳过多多洛夫和加农之间的塔楼逃脱序列。" },
    { "Skips Link's taking breath animation after coming up from water. ", "跳过林克从水中浮出后的呼吸动画。" },
    { "Skips the Frogs' Ocarina Game.", "跳过青蛙的陶笛游戏。" },
    { "Skips the Lost Woods Ocarina Memory Game.", "跳过迷失森林陶笛记忆游戏。" },
    { "Skips the Shooting Gallery minigame.", "跳过射击场小游戏。" },
    { "Sky", "天空" },
    { "Sky Gradient", "天空渐变" },
    { "Slab Depth", "板深度" },
    { "Slab Rise", "板上升" },
    { "Slow Text Speed: %dx", "慢速文本速度：%d 倍" },
    { "Small", "小" },
    { "Solve Amy's Puzzle", "解开艾米的谜题" },
    { "Sound Effects Volume: %d %%", "音效音量：%d %%" },
    { "Space between text characters (useful for HD font textures).", "文本字符之间的间距（对 HD 字体纹理有用）。" },
    { "Spawn Bean Skulltula Faster", "更快生成豆荚黄金骷髅" },
    { "Spawn with Full Health", "以满生命生成" },
    { "Spawned Enemies Ignored Ingame", "生成的敌人在游戏内被忽略" },
    { "Speak to Navi with L but enter First-Person Camera with C-Up.", "用 L 与娜薇交谈，但用 C 上进入第一人称相机。" },
    { "Speed Modifier", "速度修改器" },
    { "Speed Traps", "速度陷阱" },
    { "Speed of the Wind Waker two-axis tumble that animates the pool's faceted ", "风之杖双轴翻滚的速度，使光池的刻面" },
    { "Speeds up animation of the pause menu, similar to Majora's Mask", "加速暂停菜单的动画，类似《玛祖拉的面具》" },
    { "Speeds up emptying animation when dumping out the contents of a bottle.", "加速倒空瓶子内容时的动画。" },
    { "Speeds up lifting Silver Rocks and Obelisks.", "加速举起银岩和方尖碑。" },
    { "Speeds up ship in Shadow Temple.", "加速暗影神殿中的船。" },
    { "Split-Screen Compare", "分屏对比" },
    { "Spoiler File", "剧透文件" },
    { "Star Brightness", "星星亮度" },
    { "Star Count", "星星数量" },
    { "Stars", "星空" },
    { "Static Explosion Radius", "静态爆炸半径" },
    { "Stops masks from automatically unequipping on certain situations:\n", "阻止面具在特定情况下自动卸下：\n" },
    { "Stops the game from freezing the player when picking up Gold Skulltula Tokens. Does not ", "阻止游戏在拾取黄金骷髅代币时冻结玩家。不会" },
    { "Sub Music Volume: %d %%", "副音乐音量：%d %%" },
    { "Sunlight Arrows", "阳光箭" },
    { "Super Tunic", "超级外衣" },
    { "Suppress Vanilla Shadows", "抑制原版阴影" },
    { "Switch Timer Multiplier", "切换计时器倍数" },
    { "Switches Link's age and reloads the area.", "切换林克的年龄并重新加载区域。" },
    { "Sword Toggle Options", "剑切换选项" },
    { "Syncs the in-game time with the real world time.", "将游戏内时间与真实世界时间同步。" },
    { "Target Switch Button Combination:", "目标切换按钮组合：" },
    { "Targetable Gold Skulltula", "可瞄准的黄金骷髅" },
    { "Targetable Hookshot Reticle", "可瞄准的钩爪准星" },
    { "Teleport Traps", "传送陷阱" },
    { "Test Notification", "测试通知" },
    { "Text", "文本" },
    { "Text Speed: %dx", "文本速度：%d 倍" },
    { "Text to Speech", "文字转语音" },
    { "Texture Filter (Needs reload)", "纹理过滤（需重新加载）" },
    { "The Kokiri are mystical beings that fade into view when approached. Enabling this will remove their ", "科克里是神秘的存在，靠近时淡入视野。启用此项将移除他们的" },
    { "The Pond Owner will not ask to confirm if you want to keep a smaller Fish.", "池塘主人不会询问你是否要保留较小的鱼。" },
    { "The ammunition at the start of the Shooting Gallery minigame as Adult.", "成人时射击场小游戏开始时的弹药。" },
    { "The ammunition at the start of the Shooting Gallery minigame as Child.", "儿童时射击场小游戏开始时的弹药。" },
    { "The amount of cuccos needed to receive bottle from Anju the Cucco Lady.", "从养鸡妇安茹处获得瓶子所需的公鸡数量。" },
    { "The crawlspace into Hyrule Castle goes straight to Zelda, skipping the guards.", "通往海拉尔城的爬行空间直达塞尔达，跳过守卫。" },
    { "The default response to Kaepora Gaebora is always that you understood what he said.", "对卡波拉·盖波拉的默认回应总是你理解了他的话。" },
    { "The log level determines which messages are printed to the console.", "日志级别决定打印到控制台的消息。" },
    { "The minimum weight for the unique Fishing Reward as a child.", "儿童时独特钓鱼奖励的最小重量。" },
    { "The minimum weight for the unique fishing reward as an adult.", "成人时独特钓鱼奖励的最小重量。" },
    { "The number of Bombchus available at the start of the Bombchu Bowling minigame.", "炸弹鼠保龄球小游戏开始时可用的炸弹鼠数量。" },
    { "The size of the item when it is picked up.", "物品被拾起时的大小。" },
    { "The skybox in the background of the File Select screen will go through the ", "文件选择屏幕背景中的天空盒将经历" },
    { "The time between groups of Leevers spawning.", "利弗群体生成之间的时间。" },
    { "These are NOT like emulator states. They do not save your game progress ", "这些与模拟器状态不同。它们不保存你的游戏进度" },
    { "These enhancements are only useful in the Randomizer mode but do not affect the randomizer logic.", "这些增强仅在随机化模式中有用，但不影响随机化逻辑。" },
    { "This allows you to advance through the game one frame at a time on command. ", "这允许你按命令逐帧推进游戏。" },
    { "This allows you to put up for shield with any two-handed weapon in hand except for Deku Sticks.", "这允许你手持任何双手武器时举起盾牌，代库木棒除外。" },
    { "This setting is disabled because: \n", "此设置已禁用，因为：\n" },
    { "This will completely erase the controls config, including registered devices.\nContinue?", "这将完全擦除控制配置，包括已注册的设备。\n继续？" },
    { "Three-Point", "三点" },
    { "Tier 1 Traps:", "第 1 层陷阱：" },
    { "Tier 2 Traps:", "第 2 层陷阱：" },
    { "Tier 3 Traps:", "第 3 层陷阱：" },
    { "Time Sync", "时间同步" },
    { "Time Travel with Song of Time", "用时之曲时间旅行" },
    { "Time of Day", "一天中的时间" },
    { "Timeless Equipment", "永恒装备" },
    { "Tints Navi's light toward her current colour. Her light is normally white, but ", "将娜薇的光调向其当前颜色。她的光通常是白色，但" },
    { "Toggle Check Tracker", "切换检查追踪器" },
    { "Toggle Entrance Tracker", "切换入口追踪器" },
    { "Toggle Fullscreen", "切换全屏" },
    { "Toggle Input Viewer", "切换输入查看器" },
    { "Toggle Item Tracker", "切换物品追踪器" },
    { "Toggle Timers Window", "切换计时器窗口" },
    { "Toggle modifier instead of holding", "切换修改器而非按住" },
    { "Toggle to change container textures to match their contents in randomizer games.\n", "切换以更改容器纹理，使其匹配随机化游戏中的内容。\n" },
    { "Toggles Fullscreen On/Off.", "切换全屏开/关。" },
    { "Toggles the Check Tracker.", "切换检查追踪器。" },
    { "Toggles the Entrance Tracker.", "切换入口追踪器。" },
    { "Toggles the Input Viewer.", "切换输入查看器。" },
    { "Toggles the Item Tracker.", "切换物品追踪器。" },
    { "Top Left", "左上" },
    { "Top Right", "右上" },
    { "Trace", "跟踪" },
    { "Transition Time", "过渡时间" },
    { "Translate Title Screen", "翻译标题屏幕" },
    { "Translate the Debug Warp Screen based on the game language.", "根据游戏语言翻译调试传送屏幕。" },
    { "Trap Options", "陷阱选项" },
    { "Trees Drop Sticks", "树掉落木棒" },
    { "Tricks/Glitches", "技巧/故障" },
    { "Turn on/off changes to the Bombchu Bowling behavior.", "开启/关闭对炸弹鼠保龄球行为的更改。" },
    { "Turn on/off changes to the Fishing behavior.", "开启/关闭对钓鱼行为的更改。" },
    { "Turn on/off changes to the Frogs' Ocarina Game behavior.", "开启/关闭对青蛙陶笛游戏行为的更改。" },
    { "Turn on/off changes to the Lost Woods Ocarina Game behavior.", "开启/关闭对迷失森林陶笛游戏行为的更改。" },
    { "Turn on/off changes to the shooting gallery behavior.", "开启/关闭对射击场行为的更改。" },
    { "Turns Bunny Hood Invisible while still maintaining its effects.", "使兔帽隐形，同时保持其效果。" },
    { "Turns off the Level of Detail setting, making models use their Higher-Poly variants at any distance.", "关闭细节层次设置，使模型在任何距离使用高多边形变体。" },
    { "Turns on OoT Beta Quest. *WARNING*: This will reset your game!", "开启 OoT 测试任务。*警告*：这将重置你的游戏！" },
    { "Turns the Static Image of Link in the Pause Menu's Equipment Subscreen ", "将暂停菜单装备子屏幕中林克的静态图像" },
    { "Twinkle Speed", "闪烁速度" },
    { "Typically, inputs that are held prior to the buffer window are not included in the buffer. This ", "通常，缓冲窗口之前按住的输入不包含在缓冲中。此" },
    { "UI", "UI" },
    { "Ultrawide (21:9)", "超宽（21:9）" },
    { "Unbreakable", "不可破坏" },
    { "Unbreakable + Always on Fire", "不可破坏 + 始终燃烧" },
    { "Unlimited Playback Time##Frogs", "无限演奏时间##Frogs" },
    { "Unlimited Playback Time##LostWoods", "无限演奏时间##LostWoods" },
    { "Unrestricted Items", "无限制物品" },
    { "Unsheathe Sword Without Slashing", "拔剑而不挥砍" },
    { "Use Custom Key Models", "使用自定义钥匙模型" },
    { "Use Custom graphics for Dungeon Keys, Big and Small, so that they can be easily told apart.", "为大小地牢钥匙使用自定义图形，以便轻松区分。" },
    { "Use Navi as a Light Source", "使用娜薇作为光源" },
    { "Use Sky", "使用天空" },
    { "Use Wind Waker default movement", "使用风之杖默认移动" },
    { "Vanilla", "原版" },
    { "Vanilla (1x)", "原版（1x）" },
    { "Viewport dimensions: {} x {}", "视口尺寸：{} x {}" },
    { "Vine/Ladder Climb Speed +%d", "藤蔓/梯子攀爬速度 +%d" },
    { "Violet", "紫罗兰" },
    { "Visual Stone of Agony", "可视痛苦之石" },
    { "Void Damage Multiplier", "虚空伤害倍数" },
    { "Void Traps", "虚空陷阱" },
    { "WWLSepFairy", "WWLSepFairy" },
    { "WWLSepNavi", "WWLSepNavi" },
    { "Warn", "警告" },
    { "Warp Point", "传送点" },
    { "Warp Points", "传送点" },
    { "Warping", "传送中" },
    { "Wearing the Bunny Hood grants a speed and jump boost like in Majora's Mask.\n", "佩戴兔帽获得类似《玛祖拉的面具》中的速度和跳跃加成。\n" },
    { "When Medallions are collected, the Medallion imprints around the Master Sword Pedestal in the Temple ", "当收集到勋章时，勋章印记会出现在时之庙大师之剑基座周围" },
    { "When a line is stable, guarantee bite. Otherwise use Default logic.", "当鱼线稳定时保证咬钩。否则使用默认逻辑。" },
    { "When loading a save, places Link at the last entrance he went through.\n", "加载存档时，将林克放在他通过的最后一个入口。\n" },
    { "When obtaining Rupees, randomize what the Rupee is called in the textbox.", "获得卢比时，随机化文本框中卢比的称呼。" },
    { "When shuffling boss souls, they'll appear as a simpler model instead of showing the boss' models.", "洗牌 Boss 灵魂时，它们会显示为更简单的模型，而非显示 Boss 的模型。" },
    { "When viewers spawn enemies, the enemy will have a name tag above them with the viewer's name.", "当观众生成敌人时，敌人在其上方会有带观众名字的名称标签。" },
    { "When you lose 4 quarters of a heart you will permanently lose that Heart Container.\n\n", "当你失去一颗心的 4 个四分之一时，你将永久失去该心之容器。\n\n" },
    { "Where the dark-to-light transition sits. Higher = more of the surface ", "明暗过渡的位置。越高 = 表面更多" },
    { "Which corner of the screen notifications appear in.", "通知出现在屏幕的哪个角落。" },
    { "Wide Door Ranges", "宽门范围" },
    { "Widescreen (16:9)", "宽屏（16:9）" },
    { "Widescreen Actor Culling", "宽屏角色剔除" },
    { "Width of the transition band. Low = a hard cel edge; high = a softer ", "过渡带的宽度。低 = 硬卡通边缘；高 = 更柔和" },
    { "Wind Waker Style", "风之杖风格" },
    { "Wind Waker's white wind streaks curling through the sky — occasionally pulling a full ", "风之杖的白色风纹在天空中卷曲，偶尔拉出完整的" },
    { "Wind Wisps", "风之精" },
    { "Windowed Fullscreen", "窗口化全屏" },
    { "Windows Audio Session API", "Windows 音频会话 API" },
    { "Wisp Amount", "风精数量" },
    { "Wisp Speed", "风精速度" },
    { "With Shuffle Speak, jabber nut model & color will be generic.", "使用洗牌对话时，喋喋坚果的模型和颜色将是通用的。" },
    { "X-Large", "特大" },
    { "https://github.com/HarbourMasters/sail", "https://github.com/HarbourMasters/sail" },
    // ---- batch 2: menu structure (top-level sections & sidebars) ----
    { "Settings", "设置" },
    { "Randomizer", "随机化" },
    { "Enhancements", "增强功能" },
    { "Network", "网络" },
    { "Dev Tools", "开发者工具" },
    { "Wind Waker Style", "风之杖风格" },
    { "General", "通用" },
    { "Audio", "音频" },
    { "Graphics", "图形" },
    { "Controls", "控制" },
    { "Input Viewer", "输入查看器" },
    { "Notifications", "通知" },
    { "Mod Menu", "模组菜单" },
    { "Locations", "地点" },
    { "Tricks/Glitches", "技巧/故障" },
    { "Plandomizer", "计划随机化" },
    { "Item Tracker", "物品追踪器" },
    { "Entrance Tracker", "入口追踪器" },
    { "Check Tracker", "检查追踪器" },
    { "Skips & Speed-ups", "跳过与加速" },
    { "Items", "物品" },
    { "Fixes", "修复" },
    { "Difficulty", "难度" },
    { "Minigames", "迷你游戏" },
    { "Extra Modes", "额外模式" },
    { "Cheats", "作弊" },
    { "Cosmetics Editor", "外观编辑器" },
    { "Audio Editor", "音频编辑器" },
    { "Gameplay Stats", "游戏统计" },
    { "Time Splits", "时间分段" },
    { "Timers", "计时器" },
    { "Crowd Control", "人群控制" },
    { "Anchor", "锚点" },
    { "Stats", "统计" },
    { "Console", "控制台" },
    { "Save Editor", "存档编辑器" },
    { "Hook Debugger", "钩子调试器" },
    { "Cel Shading", "卡通渲染" },
    { "Lights", "光照" },
    { "Sky", "天空" },

    // ---- batch 3: common actions & labels ----
    { "Save", "保存" },
    { "Load", "加载" },
    { "Reset", "重置" },
    { "Reset All", "全部重置" },
    { "Apply", "应用" },
    { "Cancel", "取消" },
    { "OK", "确定" },
    { "Close", "关闭" },
    { "Close Menu (Esc)", "关闭菜单 (Esc)" },
    { "Quit", "退出" },
    { "Quit SoH", "退出 SoH" },
    { "Default", "默认" },
    { "Defaults", "默认值" },
    { "Enable", "启用" },
    { "Disable", "禁用" },
    { "Enabled", "已启用" },
    { "Disabled", "已禁用" },
    { "On", "开" },
    { "Off", "关" },
    { "True", "真" },
    { "False", "假" },
    { "None", "无" },
    { "Custom", "自定义" },
    { "All", "全部" },
    { "Search", "搜索" },
    { "Search...", "搜索..." },
    { "Clear", "清除" },
    { "Yes", "是" },
    { "No", "否" },
    { "Pause", "暂停" },
    { "Play", "播放" },
    { "Stop", "停止" },
    { "Back", "返回" },
    { "Next", "下一步" },
    { "Previous", "上一步" },
    { "Add", "添加" },
    { "Remove", "移除" },
    { "Delete", "删除" },
    { "Edit", "编辑" },
    { "Open", "打开" },
    { "Volume", "音量" },
    { "Resolution", "分辨率" },
    { "Fullscreen", "全屏" },
    { "Windowed", "窗口化" },
    { "VSync", "垂直同步" },
    { "Width", "宽度" },
    { "Height", "高度" },
    { "FPS", "帧率" },
    { "Menu Settings", "菜单设置" },
    { "Menu Theme", "菜单主题" },
    { "Interface Language", "界面语言" },
    { "Select the display language for the menu interface.", "选择菜单界面的显示语言。" },
    { "Are you sure you want to quit SoH?", "确定要退出 SoH 吗？" },
    { "This setting is disabled because: \n", "此设置已禁用，原因是：\n" },
    { "English", "英语" },
    { "简体中文", "简体中文" },

    // ---- batch 4: disabled-reason tooltips ----
    { "Disabling VSync not supported", "不支持禁用垂直同步" },
    { "Windowed Fullscreen not supported", "不支持窗口化全屏" },
    { "Multi-viewports not supported", "不支持多视口" },
    { "Available Only on DirectX", "仅在 DirectX 上可用" },
    { "Not Available on DirectX", "在 DirectX 上不可用" },
    { "Match Refresh Rate is Enabled", "已启用匹配刷新率" },
    { "Advanced Resolution Enabled", "已启用高级分辨率" },
    { "Vertical Resolution Toggle Enabled", "已启用垂直分辨率切换" },
    { "N64 Mode Enabled", "已启用 N64 模式" },
    { "Save Not Loaded", "未加载存档" },
    { "Debug Mode is Disabled", "调试模式已禁用" },
    { "Frame Advance is Disabled", "帧前进已禁用" },
    { "Advanced Resolution is Disabled", "高级分辨率已禁用" },
    { "Vertical Resolution Toggle is Off", "垂直分辨率切换已关闭" },

    // __TRANSLATION_TAIL__
};

static std::string TranslateImpl(const std::string& text) {
    if (text.empty()) {
        return text;
    }
    // The Interface Language combo box stores an integer key (0 = English, 1 = Simplified Chinese).
    int32_t lang = CVarGetInteger(CVAR_SETTING("Menu.InterfaceLanguage"), 0);
    if (lang == 1) {
        auto it = gChineseTable.find(text);
        if (it != gChineseTable.end()) {
            return it->second;
        }
    }
    return text;
}

// Decode a UTF-8 string and collect every non-ASCII codepoint it uses.
static void CollectCodepoints(const std::string& s, std::set<uint32_t>& out) {
    const unsigned char* p = reinterpret_cast<const unsigned char*>(s.data());
    size_t i = 0;
    while (i < s.size()) {
        unsigned char c = p[i];
        uint32_t cp;
        if (c < 0x80) {
            cp = c;
            i += 1;
        } else if ((c & 0xE0) == 0xC0) {
            cp = ((c & 0x1F) << 6) | (p[i + 1] & 0x3F);
            i += 2;
        } else if ((c & 0xF0) == 0xE0) {
            cp = ((c & 0x0F) << 12) | ((p[i + 1] & 0x3F) << 6) | (p[i + 2] & 0x3F);
            i += 3;
        } else if ((c & 0xF8) == 0xF0) {
            cp = ((c & 0x07) << 18) | ((p[i + 1] & 0x3F) << 12) | ((p[i + 2] & 0x3F) << 6) |
                 (p[i + 3] & 0x3F);
            i += 4;
        } else {
            i += 1;
            continue;
        }
        // Keep everything that isn't plain ASCII so the default font (which already
        // covers ASCII) is not duplicated, but CJK / fullwidth / curly quotes are.
        if (cp >= 0x80) {
            out.insert(cp);
        }
    }
}

void RegisterLocalization() {
    StringHelper::SetTranslator(TranslateImpl);

    // Merge a Simplified-Chinese font into ImGui's default font so the menu can
    // actually render Chinese glyphs. We only add the codepoints that appear in our
    // translation table, which keeps the atlas small and startup fast.
    static bool sFontMerged = false;
    if (sFontMerged) {
        return;
    }
    sFontMerged = true;

    std::string fontPath = Ship::Context::GetPathRelativeToAppDirectory("DroidSansFallback.ttf");
    if (!std::filesystem::exists(fontPath)) {
        return;
    }

    std::set<uint32_t> codepoints;
    for (const auto& pair : gChineseTable) {
        CollectCodepoints(pair.second, codepoints);
    }

    std::vector<ImWchar> ranges;
    for (uint32_t cp : codepoints) {
        ranges.push_back(static_cast<ImWchar>(cp));
        ranges.push_back(static_cast<ImWchar>(cp));
    }
    ranges.push_back(0);

    ImGuiIO& io = ImGui::GetIO();
    ImFontConfig cfg;
    cfg.MergeMode = true;
    cfg.PixelSnapH = true;
    // Match the default menu font size (13.0f, see libultraship Gui.cpp).
    io.Fonts->AddFontFromFileTTF(fontPath.c_str(), 13.0f, &cfg, ranges.data());
}

} // namespace SohGui
